---
- name: "Install needed cli"
  hosts: localhost
  become_method: ansible.builtin.sudo
  become: true
  vars:
    clusterctl_version: "v1.10.2"
    talosctl_version: "v1.9.4"
    terraform_version: "1.12.0"
    gitleaks_version: "8.26.0"
    k9s_version: "v0.50.6"
    argocd_version: "v3.0.1"
    updatecli_version: "v0.100.0"
    tofu_version: "1.7.8"
    vault_version: "1.19.4"
  tasks:
    - name: "Update and upgrade apt packages"
      ansible.builtin.apt:
        update_cache: "yes"
        upgrade: "yes"
    - name: "Install curl"
      ansible.builtin.apt:
        name: curl
        state: present
    - name: Install clusterctl
      ansible.builtin.include_role:
        name: clusterctl
    - name: Install talosctl
      ansible.builtin.include_role:
        name: talosctl
    - name: Install terraform
      ansible.builtin.include_role:
        name: terraform
    - name: Install gitleaks
      ansible.builtin.include_role:
        name: gitleaks
    - name: Install k9s
      ansible.builtin.include_role:
        name: k9s
    - name: Install ArgoCD CLI
      ansible.builtin.include_role:
        name: argocd
    - name: Install updatecli
      ansible.builtin.include_role:
        name: updatecli
    - name: Install tofu
      ansible.builtin.include_role:
        name: opentofu
    - name: Install vault
      ansible.builtin.include_role:
        name: vault
