apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: che-cluster-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: "https://github.com/batleforc/weebo-si"
    path: "che-cluster.argo/helm/che-in"
    helm:
      releaseName: che-main
  destination:
    name: che-cluster
    namespace: "default"
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
