apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: vpn-only
  namespace: traefik
spec:
  ipAllowList:
    sourceRange:
      - 100.113.84.92/16
      - 10.244.0.0/16
      - fd00:10:244::/56
      - 10.96.0.0/12
      - fd00:10:96::/112
      - 10.245.0.0/16
      - 15.112.0.0/12
