---
apiVersion: v1
kind: Service
metadata:
  name: dns-server
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: dns-server
  annotations:
    {{ toYaml .Values.annotations | nindent 4 }}
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: loop
      protocol: TCP
      port: 953
      targetPort: 953
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: dns-server
  type: LoadBalancer
