---
apiVersion: v1
kind: Service
metadata:
  name: dns-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: dns-server
  annotations:
    metallb.universe.tf/address-pool: one
    metallb.io/ip-allocated-from-pool: one
    metallb.universe.tf/allow-shared-ip: one
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: loop
      protocol: TCP
      port: 953
      targetPort: 953
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: dns-server
  type: LoadBalancer
