{{- if .Values.harbor.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: "https://github.com/batleforc/weebo-si"
    path: "all-in-one.argo/helm/harbor"
    helm:
      releaseName: harbor
  destination:
    name: in-cluster
    namespace: "harbor"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
{{- end -}}