{{- if .Values.kubevirt.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://github.com/batleforc/weebo-si'
    path: 'all-in-one.argo/helm/main-step2'
    helm:
      releaseName: step2
  destination:
    name: in-cluster
    namespace: 'default'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
{{- end -}}