apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
  namespace: netbird
  annotations:
    sync-waves.argoproj.io/sync-wave: "5"
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: auth
  target:
    name: netbird-auth
    template:
      type: Opaque
      data:
        url: '{{ printf "{{"}} .url }}'
        client_id: '{{ printf "{{"}} .client_id }}'
        client_secret: '{{ printf "{{"}} .client_secret }}'
  data:
    - secretKey: idpClientID
      remoteRef:
        key: mc-authentik/netbird/auth
        property: NETBIRD_AUTH_CLIENT_ID
    - secretKey: idpServiceAccountPassword
      remoteRef:
        key: mc-authentik/netbird/auth
        property: NETBIRD_IDP_MGMT_EXTRA_PASSWORD
    - secretKey: idpServiceAccountUser
      remoteRef:
        key: mc-authentik/netbird/auth
        property: NETBIRD_IDP_MGMT_EXTRA_USERNAME
