apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coturn-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  syncPolicy:
    automated: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netbird
  source:
    #chart: coturn
    #repoURL: https://small-hack.github.io/coturn-chart
    #targetRevision: 9.1.0
    repoURL: 'https://github.com/batleforc/weebo-si'
    path: 'all-in-one.argo/helm/coturn-app
    helm:
      releaseName: coturn
      valuesObject:
        service:
          type: LoadBalancer
          annotations:
            lbipam.cilium.io/sharing-key: "weebo-gate"
            lbipam.cilium.io/ips: "{{ .Values.outboundIps }}"
            lbipam.cilium.io/sharing-cross-namespace: "*"
        coturn:
          realm: "turn.4.weebo.fr"
          auth:
            existingSecret: "netbird-auth"
            secretKeys:
              username: "turnServerUser"
              password: "turnServerPassword"
        certificate:
          enabled: true
          issuerName: outbound
          host: "turn.4.weebo.fr"
