apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: netbird
    repoURL: https://netbirdio.github.io/helms
    # https://github.com/bank-vaults/vault-operator/pkgs/container/helm-charts%2Fvault-operator
    targetRevision: 1.8.0
    helm:
      releaseName: netbird
      valuesObject:
        fullnameOverride: netbird
        management:
          configmap: |-
            {
              "Stuns": [
                {
                  "Proto": "udp",
                  "URI": "{{ printf "{{"}} .STUN_SERVER }}",
                  "Username": "",
                  "Password": ""
                }
              ],
              "TURNConfig": {
                "TimeBasedCredentials": false,
                "CredentialsTTL": "12h0m0s",
                "Secret": "secret",
                "Turns": [
                  {
                    "Proto": "udp",
                    "URI": "{{ printf "{{"}} .TURN_SERVER }}",
                    "Username": "{{ printf "{{"}} .TURN_SERVER_USER }}",
                    "Password": "{{ printf "{{"}} .TURN_SERVER_PASSWORD }}"
                  }
                ]
              },
              "Relay": {
                "Addresses": ["rels://netbird.4.weebo.fr:443/relay"],
                "CredentialsTTL": "24h",
                "Secret": "{{ printf "{{"}} .RELAY_PASSWORD }}"
              },
              "Signal": {
                "Proto": "https",
                "URI": "netbird.4.weebo.fr:443",
                "Username": "",
                "Password": ""
              },
              "Datadir": "/var/lib/netbird/",
              "DataStoreEncryptionKey": "{{ printf "{{"}} .DATASTORE_ENCRYPTION_KEY }}",
              "HttpConfig": {
                "LetsEncryptDomain": "",
                "CertFile": "",
                "CertKey": "",
                "AuthAudience": "{{ printf "{{"}} .IDP_CLIENT_ID }}",
                "AuthIssuer": "https://login.4.weebo.fr/application/o/netbird/",
                "AuthUserIDClaim": "",
                "AuthKeysLocation": "https://login.4.weebo.fr/application/o/netbird/jwks/",
                "OIDCConfigEndpoint": "{{ printf "{{"}} .OIDC_CONFIG_ENDPOINT }}",
                "IdpSignKeyRefreshEnabled": false
              },
              "IdpManagerConfig": {
                "ManagerType": "authentik",
                "ClientConfig": {
                  "Issuer": "https://login.4.weebo.fr/application/o/netbird",
                  "TokenEndpoint": "https://login.4.weebo.fr/application/o/token/",
                  "ClientID": "{{ printf "{{"}} .IDP_CLIENT_ID }}",
                  "ClientSecret": "{{ printf "{{"}} .IDP_CLIENT_SECRET }}",
                  "GrantType": "client_credentials"
                },
                "ExtraConfig": {
                  "Password": "{{ printf "{{"}} .IDP_SERVICE_ACCOUNT_PASSWORD }}",
                  "Username": "{{ printf "{{"}} .IDP_SERVICE_ACCOUNT_USER }}"
                },
                "Auth0ClientCredentials": null,
                "AzureClientCredentials": null,
                "KeycloakClientCredentials": null,
                "ZitadelClientCredentials": null
              },
              "DeviceAuthorizationFlow": {
                "Provider": "hosted",
                "ProviderConfig": {
                  "ClientID": "{{ printf "{{"}} .IDP_CLIENT_ID }}",
                  "ClientSecret": "",
                  "Domain": "login.4.weebo.fr",
                  "Audience": "{{ printf "{{"}} .IDP_CLIENT_ID }}",
                  "TokenEndpoint": "https://login.4.weebo.fr/application/o/token/",
                  "DeviceAuthEndpoint": "https://login.4.weebo.fr/application/o/device/",
                  "AuthorizationEndpoint": "",
                  "Scope": "openid",
                  "UseIDToken": false,
                  "RedirectURLs": null
                }
              },
              "PKCEAuthorizationFlow": {
                "ProviderConfig": {
                  "ClientID": "{{ printf "{{"}} .IDP_CLIENT_ID }}",
                  "ClientSecret": "",
                  "Domain": "",
                  "Audience": "{{ printf "{{"}} .IDP_CLIENT_ID }}",
                  "TokenEndpoint": "https://login.4.weebo.fr/application/o/token/",
                  "DeviceAuthEndpoint": "",
                  "AuthorizationEndpoint": "https://login.4.weebo.fr/application/o/authorize/",
                  "Scope": "openid profile email offline_access api",
                  "UseIDToken": false,
                  "RedirectURLs": ["http://localhost:53000"]
                }
              },
              "StoreConfig": {
                "Engine": "sqlite"
              },
              "ReverseProxy": {
                "TrustedHTTPProxies": null,
                "TrustedHTTPProxiesCount": 0,
                "TrustedPeers": null
              }
            }
          persistentVolume:
            enabled: true
          envFromSecret:
            STUN_SERVER: netbird-auth/stunServer
            TURN_SERVER: netbird-auth/turnServer
            TURN_SERVER_USER: netbird-auth/turnServerUser
            TURN_SERVER_PASSWORD: netbird-auth/turnServerPassword
            RELAY_PASSWORD: netbird-auth/relayPassword
            IDP_CLIENT_ID: netbird-auth/idpClientID
            IDP_SERVICE_ACCOUNT_USER: netbird-auth/idpServiceAccountUser
            IDP_SERVICE_ACCOUNT_PASSWORD: netbird-auth/idpServiceAccountPassword
            DATASTORE_ENCRYPTION_KEY: netbird-auth/datastoreEncryptionKey
            OIDC_CONFIG_ENDPOINT: netbird-auth/oidcConfigEndpoint
            IDP_CLIENT_SECRET: netbird-auth/clientSecret

        relay:
          envFromSecret:
            NB_AUTH_SECRET: netbird-auth/relayPassword
          env:
            NB_LOG_LEVEL: info
            NB_LISTEN_ADDRESS: ":33080"
            NB_EXPOSED_ADDRESS: rels://netbird.4.weebo.fr:443/relay

        dashboard:
          enabled: true
          env:
            # Endpoints
            NETBIRD_MGMT_API_ENDPOINT: https://netbird.4.weebo.fr:443
            NETBIRD_MGMT_GRPC_API_ENDPOINT: https://netbird.4.weebo.fr:443
            # OIDC
            AUTH_CLIENT_SECRET:
            AUTH_AUTHORITY: https://login.4.weebo.fr/application/o/netbird/
            USE_AUTH0: false
            AUTH_SUPPORTED_SCOPES: openid profile email offline_access api
            AUTH_REDIRECT_URI:
            AUTH_SILENT_REDIRECT_URI:
            NETBIRD_TOKEN_SOURCE: accessToken
            NGINX_SSL_PORT:
            LETSENCRYPT_DOMAIN:
            LETSENCRYPT_EMAIL:
          envFromSecret:
            AUTH_CLIENT_ID: netbird-auth/idpClientID
            AUTH_AUDIENCE: netbird-auth/idpClientID

        extraManifests:
          - apiVersion: traefik.io/v1alpha1
            kind: IngressRoute
            metadata:
              name: netbird
              labels:
                argocd.argoproj.io/instance: netbird
            spec:
              entryPoints:
                - websecure
              routes:
                - kind: Rule
                  match: Host(`netbird.4.weebo.fr`) && !PathPrefix(`/api`) && !PathPrefix(`/management`) && !PathPrefix(`/signalexchange`) && !PathPrefix(`/relay`)
                  services:
                    - name: netbird-dashboard
                      namespace: netbird
                      passHostHeader: true
                      port: 80
                - kind: Rule
                  match: Host(`netbird.4.weebo.fr`) && PathPrefix(`/api`)
                  services:
                    - name: netbird-management
                      namespace: netbird
                      passHostHeader: true
                      port: 80
                - kind: Rule
                  match: Host(`netbird.4.weebo.fr`) && PathPrefix(`/relay`)
                  services:
                    - name: netbird-relay
                      namespace: netbird
                      passHostHeader: true
                      port: 33080
                - kind: Rule
                  match: Host(`netbird.4.weebo.fr`) && PathPrefix(`/management`)
                  services:
                    - name: netbird-management
                      namespace: netbird
                      passHostHeader: true
                      port: 80
                      scheme: h2c
                - kind: Rule
                  match: Host(`netbird.4.weebo.fr`) && PathPrefix(`/signalexchange`)
                  services:
                    - name: netbird-signal
                      namespace: netbird
                      passHostHeader: true
                      port: 80
                      scheme: h2c
              tls:
                secretName: "netbird-certificate"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netbird
