apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: auth
  namespace: netbird
  annotations:
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    vault:
      server: "https://vault.vault:8200"
      path: "mc-authentik"
      caProvider:
        type: Secret
        name: vault-tls
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "auth-read"
          serviceAccountRef:
            name: "default"
