apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    #config.k8s.io/owning-inventory: talos-bootstrap-manifests-inventory
    app.kubernetes.io/managed-by: argocd
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153

        rewrite name regex (.*)\.weebo\.poc traefik.traefik.svc.cluster.local answer auto

        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }