{{- if .Values.pushTsig.enabled -}}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: "tsig-store"
  namespace: cert-manager
  annotations:
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    vault:
      server: "https://vault.vault:8200"
      path: "mv"
      caProvider:
        type: Secret
        name: vault-tls
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "auth-read"
          serviceAccountRef:
            name: "default"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-tsig
  namespace: cert-manager
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: tsig-store
  target:
    name: tsig-key-secret
  data:
  - secretKey: tsig.key.secret
    remoteRef:
      key: mv/cert-manager/tsig
      property: tsig.key.secret
{{- end -}}
