apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: kubevirt-manager
  labels:
    app.kubernetes.io/name: kubevirt-manager
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`kubevirt-manager.4.weebo.fr`)
      priority: 10
      services:
        - name: kubevirt-manager
          namespace: kubevirt-manager
          port: 8080
          passHostHeader: true
      middlewares:
        - name: vpn-only
          namespace: traefik
        - name: authentik
          namespace: authentik
        # - name: outpost-vpn
        #   namespace: traefik
    - kind: Rule
      match: Host(`kubevirt-manager.4.weebo.fr`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - name: authentik-server
          namespace: authentik
          port: 80
          passHostHeader: true
      middlewares:
        - name: vpn-only
          namespace: traefik
  tls:
    secretName: kubevirt-manager-certificate
