{{- if .Values.vaultInstance.enabled -}}
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: openbao
  namespace: vault
spec:
  size: 1
  image: openbao/openbao:latest

  # Configuration du backend de stockage
  config:
    storage:
      raft:
        path: "/openbao/data"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true
    api_addr: http://openbao:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    ui: true

  # ServiceAccount
  serviceAccount: openbao

  vaultContainerSpec:
    name: vault
    volumeMounts:
    - mountPath: /openbao/config
      name: vault-config
    - mountPath: /openbao/data
      name: openbao

  # Volumes pour la persistance
  volumeClaimTemplates:
    - metadata:
        name: openbao
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  # PodSpec via podAnnotations et vaultPodSpec
  vaultPodSpec:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault

{{- end -}}
