apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: outpost-vpn
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: vpn-only
        namespace: traefik
      - name: authentik
        namespace: authentik
