network:
  vip: 192.168.100.40
  port: 6443
  dnsServers:
  - 192.168.100.11
  - 8.8.8.8
  gateway: 192.168.100.1
  prefix: 20
  addresses: 192.168.100.41-192.168.100.50

extensions:
  qemuGuestAgent:
    image: ghcr.io/siderolabs/qemu-guest-agent:9.2.3

argo:
  local: false
  main: false

dns:
  enabled: true
  wildcard: true
  base: weebo.poc
  name: "{{.Release.Name}}"

cilium:
  version: 1.17.3
  enabled: true
  ipv6: false
  ipv4: true
  podSubnets:
  - 10.244.0.0/16
  #- 2001:db8:7653:299:cafe:0::/96
  serviceSubnets:
  - 10.96.0.0/12
  #- 2001:db8:7653:299:cafe:1::/96

kyverno:
  enabled: true
  version: 3.4.1
  policies: 3.4.1

certManager:
  enabled: true
  version: 1.17.2
  installCRDs: true

trustManager:
  enabled: true
  version: 0.17.1

traefik:
  enabled: true
  version: 35.2.0
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2
    sablier:
      moduleName: github.com/sablierapp/sablier
      version: v1.9.0

kubernetes:
  version: v1.33.0
  labels:
    argoHelmInstall: enabled

controlPlane:
  installImage: factory.talos.dev/nocloud-installer/22300f9a27b3f9398e6cb13526ec528c03769c59b041f70515e0cbe4ad775912:v1.10.0
  version: v1.10
  replicas: 1
  allowScheduling: true
  tccm: true
  cloudProvider: https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml

proxmox:
  allowedNodes:
  - weebo4
  nodeConf:
    node: weebo4
    disk:
      name: scsi0
      sizeGb: 50
    memoryMiB: 8192
    network: vmbr1
    templateID: 9998
    cpu:
      cores: 2
      sockets: 1
