network:
  vip: 192.168.100.40
  port: 6443
  dnsServers:
  - 192.168.100.11
  - 8.8.8.8
  gateway: 192.168.100.1
  prefix: 20
  addresses: 192.168.100.41-192.168.100.50

extensions:
  qemuGuestAgent:
    image: ghcr.io/siderolabs/qemu-guest-agent:10.0.2

argo:
  local: false
  main: false
  apps:
    enabled: false
    version: 8.0.17
    prefix: argo
    rbac:
      scopes: '[groups]'
      policy: |
        g, admin, role:admin
        g, dev, role:dev
        g, reader, role:readonly
        g, weebo_admin, role:admin
        g, authentik Admins, role:admin

externalSecrets:
  enabled: false
  version: 0.17.0
  vault:
    enabled: false
    version: 4.4.0

storage:
  local:
    enabled: true
  longhorn:
    enabled: false
    version: v1.8.1
  rook:
    enabled: false
    version: v1.16.8
    imageVersion: v19

dns:
  enabled: true
  wildcard: true
  base: weebo.poc
  name: "{{.Release.Name}}"

cilium:
  version: 1.17.4
  enabled: true
  ipv6: false
  ipv4: true
  podSubnets:
  - 10.244.0.0/16
  #- 2001:db8:7653:299:cafe:0::/96
  serviceSubnets:
  - 10.96.0.0/12
  #- 2001:db8:7653:299:cafe:1::/96

certificate:
  rootCA:
    url: https://vault.capi.weebo.poc/v1/pki/issuer/default/json
  subCA:
    url: https://vault.capi.weebo.poc/v1/pki_int/issuer/default/json

kyverno:
  enabled: false
  version: 3.4.2
  policies: 3.4.2
  reporter: 3.1.4

certManager:
  enabled: true
  version: 1.18.0
  installCRDs: true

trustManager:
  enabled: true
  version: 0.17.1

traefik:
  enabled: false
  version: 36.3.0
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.4
    sablier:
      moduleName: github.com/sablierapp/sablier
      version: v1.9.0

vault:
  enabled: false
  version: 1.21.3

bootstrap:
  vaultProviderVersion: "4.4.0"

kubernetes:
  version: v1.33.1
  labels:
    argoHelmInstall: disabled

controlPlane:
  installImage: factory.talos.dev/nocloud-installer/ac8870ab0fc06e25c9cc68d4ba3e2c4d5d2ce86d7525cda4aad57602e64fc4e3:v1.10.4
  version: v1.10.4
  replicas: 1
  allowScheduling: true
  tccm: true
  cloudProvider: https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml

worker:
  installImage: factory.talos.dev/nocloud-installer/ac8870ab0fc06e25c9cc68d4ba3e2c4d5d2ce86d7525cda4aad57602e64fc4e3:v1.10.4
  version: v1.10.4
  replicas: 1
  enabled: false

proxmox:
  allowedNodes:
  - weebo4
  nodeConf:
    node: weebo4
    disk:
      name: scsi0
      sizeGb: 20
    memoryMiB: 6144
    network: vmbr1
    templateID: 9998
    cpu:
      cores: 2
      sockets: 2
  workerConf:
    node: weebo4
    templateID: 9998
    disk:
      name: scsi0
      sizeGb: 50
    memoryMiB: 8192
    network: vmbr1
    cpu:
      cores: 2
      sockets: 2
