{{- if .Values.obi.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  syncPolicy:
    automated: {}
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
    - CreateNamespace=true
  source:
    chart: opentelemetry-ebpf-instrumentation
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: {{ .Values.obi.version }}
    helm:
      releaseName: obi
      valuesObject:
        volumes:
          - name: bpffs
            hostPath:
              path: /sys/fs/bpf
              type: Directory

        volumeMounts:
          - name: bpffs
            mountPath: /sys/fs/bpf
            mountPropagation: HostToContainer
        podAnnotations:
          vault.security.banzaicloud.io/vault-addr: "https://openbao.vault:8200"
          vault.security.banzaicloud.io/vault-role: "auth-read"
          vault.security.banzaicloud.io/vault-path: "kubernetes"
          vault.security.banzaicloud.io/vault-tls-secret: "openbao-tls"
        env:
          OTEL_EBPF_KUBE_CLUSTER_NAME: "weebo-si"
          OTEL_EXPORTER_OTLP_HEADERS: "authorization=${OTEL_EXPORTER_OTLP_HEADERS_AUTHENTICATION}"
          OTEL_EXPORTER_OTLP_HEADERS_AUTHENTICATION: "vault:mv/data/obi/config#API_KEY"
        config:
          create: true
          data:
            cluster_name: "weebo-si"
            otel_traces_export:
              endpoint: "http://clickstack-otel-collector.monitoring:4317"
            otel_metrics_export:
              endpoint: "http://clickstack-otel-collector.monitoring:4318"
            network:
              enabled: true
  destination:
    name: in-cluster
    namespace: obi

{{- end -}}
