{{- if .Values.zitadel.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  source:
    chart: zitadel
    repoURL: https://charts.zitadel.com
    targetRevision: {{ .Values.zitadel.version }}
    helm:
      releaseName: zitadel
      valuesObject:
        podAnnotations:
          vault.security.banzaicloud.io/vault-addr: "https://openbao.vault:8200"
          vault.security.banzaicloud.io/vault-role: "auth-read"
          vault.security.banzaicloud.io/vault-path: "kubernetes"
          vault.security.banzaicloud.io/vault-tls-secret: "openbao-tls"
        postgresql:
          enabled: true
          commonAnnotations:
            helm.sh/hook: pre-install
            helm.sh/hook-weight: "-1"
          auth:
            database: zitadel
            username: zitadel
            password: zitadel
            postgresPassword: zitadel
          primary:
            persistence:
              enabled: false

        zitadel:
          masterkey: "vault:mv/data/zitadel/config#masterkey"

          configmapConfig:
            ExternalDomain: {{ .Values.zitadel.dns }}   # replace with your domain or IP
            ExternalPort: 80            # replace with the port your ingress controller listens on
            ExternalSecure: false
            TLS:
              Enabled: false
            FirstInstance:
              Org:
                Human:
                  UserName: zitadel-admin
                  Email: zitadel-admin@zitadel.localhost
                  Password: "Password1!"
                  PasswordChangeRequired: false

        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: {{ .Values.zitadel.dns }}
              paths:
                - path: /
                  pathType: Prefix

        login:
          ingress:
            enabled: true
            className: traefik
            hosts:
              - host: {{ .Values.zitadel.dns }}
                paths:
                  - path: /ui/v2/login
                    pathType: Prefix
  destination:
    name: "in-cluster"
    namespace: zitadel
{{- end -}}
