[tools]
k9s = "latest"
kubectl = "latest"
pulumi = "latest"
task = "latest"
argocd = "latest"
cilium-cli = "latest"
cilium-hubble = "latest"
helm-ls = "latest"
helm = "latest"
gitleaks = "latest"
cocogitto = "latest"
go = "latest"
"kkrew:cilium-policy-gen" = "latest"
"kkrew:tree" = "latest"
"github:nilic/kubectl-netshoot" = "latest"
claude = "latest"
talosctl = "latest"
fnox = "latest"
vault = "latest"
"github:janosmiko/lfk" = "latest"
popeye = "latest"
"github:kubescape/kubescape" = { version = "latest" }
"cargo:sofka" = "latest"

[plugins]
kkrew = "https://github.com/soupglasses/mise-krew"
