version: "3"

dotenv: [".env"]

includes:
  pulunit: 1.pulu-init/Taskfile.yaml
  puluconf: 1.pulu-conf/Taskfile.yaml
  argo: 0.task/argo.yaml
  vpn: 0.task/argo.yaml

tasks:
  init:
    desc: "Init project"
    cmds:
      - cog install-hook -a -o
  k:
    desc: "Run kubectl commands on the cluster"
    silent: true
    env:
      KUBECONFIG: 0.config/kubeconfig.yaml
    cmds:
      - kubectl {{ .CLI_ARGS }}
  docs:run:
    dir: 0.docs
    cmds:
      - npm run dev
  t:
    env:
      TALOSCONFIG: "0.config/talosconfig2.yaml"
    cmds:
      - talosctl {{ .CLI_ARGS }}
