version: "3"

dotenv: [".env"]

includes:
  pulunit: 1.pulu-init/Taskfile.yaml
  puluconf: 1.pulu-conf/Taskfile.yaml
  argo: 0.task/argo.yaml
  vpn: 0.task/vpn.yaml
  vault: 0.task/vault.yaml

tasks:
  init:
    desc: "Init project"
    cmds:
      - cog install-hook -a -o
  k:
    desc: "Run kubectl commands on the cluster"
    silent: true
    env:
      KUBECONFIG: 0.config/kubeconfig.yaml
    cmds:
      - kubectl {{ .CLI_ARGS }}
  k-oidc:
    silent: true
    env:
      KUBECONFIG: 0.config/kubeconfig.oidc.yaml
    cmds:
      - kubectl {{ .CLI_ARGS }}
  docs:run:
    dir: 0.docs
    cmds:
      - npm run dev
  t:
    env:
      TALOSCONFIG: "0.config/talosconfig2.yaml"
    cmds:
      - talosctl {{ .CLI_ARGS }}
  k9s:
    env:
      KUBECONFIG: 0.config/kubeconfig.yaml
    cmds:
      - k9s
  lfk:
    env:
      KUBECONFIG: 0.config/kubeconfig.oidc.yaml
    cmds:
      - lfk {{ .CLI_ARGS }}
  c:
    env:
      KUBECONFIG: 0.config/kubeconfig.yaml
    cmds:
      - cilium {{ .CLI_ARGS }}
  create-kubeconfig-oidc:
    vars:
      OIDC_CLIENT_ID:
        sh: task k-- get secret -n zitadel cluster-auth -o jsonpath='{.data.clientID}' | base64 -d
      server_url:
        sh: cat 0.config/kubeconfig.yaml | yq .clusters[0].cluster.server
      server_ca:
        sh: cat 0.config/kubeconfig.yaml | yq .clusters[0].cluster."certificate-authority-data"
    cmds:
      - cp 0.config/kubeconfig.oidc-template.yaml 0.config/kubeconfig.oidc.yaml
      - yq e -i '.users[0].user.exec.args[3] = "--oidc-client-id={{ .OIDC_CLIENT_ID }}"' 0.config/kubeconfig.oidc.yaml
      - yq e -i '.clusters[0].cluster.server = "{{ .server_url }}"' 0.config/kubeconfig.oidc.yaml
      - yq e -i '.clusters[0].cluster."certificate-authority-data" = "{{ .server_ca }}"' 0.config/kubeconfig.oidc.yaml
