policies:
  - name: golang
    config:
      - .updatecli/manifest/golang.yaml
    values:
      - .updatecli/vars.yaml
  - name: npm
    config:
      - .updatecli/manifest/npm.yaml
    values:
      - .updatecli/vars.yaml
  - name: helm
    config:
      - .updatecli/manifest/helm.yaml
    values:
      - .updatecli/vars.yaml
  - name: githubaction
    config:
      - .updatecli/manifest/gh-action.yaml
    values:
      - .updatecli/vars.yaml
