policies:
- name: install-cli
  config:
  - ./0.updatecli/setup-host/clusterctl.yaml
  - ./0.updatecli/setup-host/terraform.yaml
  - ./0.updatecli/setup-host/gitleaks.yaml
  - ./0.updatecli/setup-host/k9s.yaml
  - ./0.updatecli/setup-host/argocd.yaml
  - ./0.updatecli/setup-host/updatecli.yaml
  - ./0.updatecli/setup-host/opentofu.yaml
  - ./0.updatecli/setup-host/vault.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Traefik
  config:
  - ./0.updatecli/traefik.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade CertManager
  config:
  - ./0.updatecli/cert-manager.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Terraform Provider
  config:
  - ./0.updatecli/terraform.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Talos
  config:
  - ./0.updatecli/talos.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Cilium
  config:
  - ./0.updatecli/cilium.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Kyverno
  config:
  - ./0.updatecli/kyverno.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade DNS
  config:
  - ./0.updatecli/dns.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Cluster API
  config:
  - ./0.updatecli/cluster-api.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade Authentik
  config:
  - ./0.updatecli/authentik.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade ArgoCD
  config:
  - ./0.updatecli/argocd.yaml
  values:
  - ./0.updatecli/values.yaml
- name: Upgrade TerraTry
  config:
  - ./0.updatecli/terra-try.yaml
  values:
  - ./0.updatecli/values.yaml