{{- range $name, $team := .Values.teams }}
{{- $spec := deepCopy $team -}}
{{- with (($spec.workspace).che).source }}
{{- if not .repoUrl }}{{ $_ := set . "repoUrl" $.Values.repo }}{{ end }}
{{- if not .targetRevision }}{{ $_ := set . "targetRevision" $.Values.branch }}{{ end }}
{{- end }}
---
# Spec from values.yaml `teams.{{ $name }}`.
apiVersion: hardening.weebo.io/v1alpha1
kind: WeeboSiTeam
metadata:
  name: {{ $name }}
spec:
  {{- toYaml $spec | nindent 2 }}
{{- end }}
