{{- if .Values.dex.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  source:
    chart: dex
    repoURL: https://charts.dexidp.io
    targetRevision: {{ .Values.dex.version }}
    helm:
      releaseName: dex
      valuesObject:
        podAnnotations:
          vault.security.banzaicloud.io/vault-addr: "https://openbao.vault:8200"
          vault.security.banzaicloud.io/vault-role: "auth-read"
          vault.security.banzaicloud.io/vault-path: "kubernetes"
          vault.security.banzaicloud.io/vault-tls-secret: "openbao-tls"
        config:
          issuer: "https://{{ .Values.dex.issuer }}"
          storage:
            type: kubernetes
            config:
              inCluster: true
          enablePasswordDB: false
          oauth2:
            skipApprovalScreen: true
          connectors:
          - type: oidc
            id: weebo
            name: weebo
            config:
              issuer: {{ .Values.dex.mainConnector.issuer }}
              clientID: {{ .Values.dex.mainConnector.clientID }}
              redirectURI: "https://dex.4.weebo.fr/dex/callback"
              clientSecret: $LAB_CLIENT_SECRET
        env:
          - name: "LAB_CLIENT_SECRET"
            value: "vault:mv/data/dex/config#LAB_CLIENT_SECRET"
          - name: "KUBE_CLIENT_SECRET"
            value: "vault:mv/data/dex/auth#KUBE_CLIENT_SECRET"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/private-key-size: "4096"
            cert-manager.io/common-name: "{{ .Values.dex.issuer }}"
            cert-manager.io/subject-organizations: "WeeboSI"
            cert-manager.io/subject-organizationalunits: "Infra"
          hosts:
          - host: {{ .Values.dex.issuer }}
            paths:
              - path: /
                pathType: ImplementationSpecific
          tls:
            - hosts:
              - {{ .Values.dex.issuer }}
              secretName: dex-tls
  destination:
    name: "in-cluster"
    namespace: dex
{{- end -}}
