{{- if .Values.s3Operator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  source:
    repoURL: {{ .Values.s3Operator.repoURL }}
    path: {{ .Values.s3Operator.path }}
    targetRevision: {{ .Values.s3Operator.version }}
    helm:
      releaseName: s3
      valuesObject:
        sts:
          tls:
            auto: true
        console:
          enabled: {{ .Values.s3Operator.console.enabled }}
          ingress:
            enabled: true
            className: {{ .Values.s3Operator.console.className }}
            hosts:
              - host: {{ .Values.s3Operator.console.hosts.host }}
            tls:
              - host: {{ .Values.s3Operator.console.hosts.host }}
                secretName: {{ .Values.s3Operator.console.hosts.secretName }}
  destination:
    namespace: {{ .Values.s3Operator.namespace }}
    name: "in-cluster"
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: s3-rustfs-operator-console-secret
      namespace: s3
      jsonPointers:
        - /data/jwt-secret
{{- end }}
