{{- if .Values.che.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: che
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: {{ .Values.che.project }}
  source:
    repoURL: '{{ .Values.repo }}'
    path: '2.argo/helm/che/main'
    targetRevision: '{{ .Values.branch }}'
    helm:
      releaseName: batlehub
      valuesObject:
        project: "{{ .Values.batlehub.project }}"
        repo: "{{ .Values.repo }}"
        branch: "{{ .Values.branch }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'eclipse-che'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
{{- end -}}
