{{- if .Values.storage.main.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: {{ .Values.storage.main.project }}
  source:
    repoURL: '{{ .Values.repo }}'
    path: '2.argo/helm/storage'
    targetRevision: '{{ .Values.branch }}'
    helm:
      releaseName: ingress
      valuesObject:
        project: "{{ .Values.storage.main.project }}"
        repo: "{{ .Values.repo }}"
        branch: "{{ .Values.branch }}"
        traefik:
          ips: "{{ .Values.traefik.ips }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'argocd'
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
{{- end -}}