apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: headlamp
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    targetRevision: 0.30.1
    helm:
      releaseName: headlamp
      valuesObject:
        config:
          baseURL: /headlamp
        volumes:
        - name: main-cluster
          secret:
            secretName: main-cluster-kubeconfig
        volumeMounts:
        - name: main-cluster
          mountPath: /kubeconfig/main-cluster
        env:
        - name: KUBECONFIG
          value: /kubeconfig/main-cluster/value
        serviceAccount:
          create: true
        extraManifests:
        - apiVersion: v1
          kind: Secret
          metadata:
            name: headlamp-secret
            namespace: default
            annotations:
              kubernetes.io/service-account.name: headlamp
          type: kubernetes.io/service-account-token

  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
