apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-app
  namespace: argocd
spec:
  project: default
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: "{{ .Values.version.helm }}"
    helm:
      releaseName: harbor-app
      valuesObject:
        portal:
          automountServiceAccountToken: true
        core:
          automountServiceAccountToken: true
          podAnnotations:
            inject-certs: "enabled"
            vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
            vault.security.banzaicloud.io/vault-role: "auth-read"
            vault.security.banzaicloud.io/vault-path: "kubernetes"
            vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        jobservice:
          automountServiceAccountToken: true
        registry:
          automountServiceAccountToken: true
        trivy:
          automountServiceAccountToken: true
        exporter:
          automountServiceAccountToken: true
          podAnnotations:
            inject-certs: "enabled"
            vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
            vault.security.banzaicloud.io/vault-role: "auth-read"
            vault.security.banzaicloud.io/vault-path: "kubernetes"
            vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        expose:
          tls:
            certSource: secret
            secret:
              secretName: harbor-tls
          ingress:
            hosts:
              core: "harbor.4.weebo.fr"
            annotations:
              cert-manager.io/cluster-issuer: "outbound"
              ingress.kubernetes.io/ssl-redirect: "true"
              ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
        externalURL: "https://harbor.4.weebo.fr"
        persistence:
          persistentVolumeClaim:
            registry:
              size: 20Gi
        harborAdminPassword: "vault:mc-authentik/data/harbor/config#HARBOR_ADMIN_PASSWORD"
        secretKey: {{ randAlphaNum 16 | quote }}
        metrics:
          enabled: true


  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  ignoreDifferences:
  - group: ''
    kind: Secret
    name: harbor-core
    namespace: harbor
    jsonPointers:
    - /data/CSRF_KEY
    - /data/secret
    - /data/tls.crt
    - /data/tls.key
  - group: ''
    kind: Secret
    name: harbor-jobservice
    namespace: harbor
    jsonPointers:
    - /data/JOBSERVICE_SECRET
  - group: ''
    kind: Secret
    name: harbor-registry
    namespace: harbor
    jsonPointers:
    - /data/REGISTRY_HTTP_SECRET
  - group: ''
    kind: Secret
    name: harbor-registry-htpasswd
    namespace: harbor
    jsonPointers:
    - /data/REGISTRY_HTPASSWD
  - group: 'apps'
    kind: Deployment
    name: harbor-core
    namespace: harbor
    jsonPointers:
    - /spec/template/metadata/annotations
  - group: 'apps'
    kind: Deployment
    name: harbor-jobservice
    namespace: harbor
    jsonPointers:
    - /spec/template/metadata/annotations
  - group: 'apps'
    kind: Deployment
    name: harbor-registry
    namespace: harbor
    jsonPointers:
    - /spec/template/metadata/annotations