apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terra-harbor
  namespace: argocd
spec:
  project: default
  source:
    path: all-in-one.argo/terra/harbor
    repoURL: "https://github.com/batleforc/weebo-si"
    targetRevision: HEAD
  destination:
    namespace: harbor
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
