apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  namespace: omni
spec:
  ingressClassName: nginx
  rules:
    - host: omni.example.com
      http:
        paths:
          - backend:
              service:
                name: internal
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - omni.example.com
      secretName: omni.example.com-tls
