ingress:
  enabled: true
  project: infra

repo: ""
branch: ""

traefik:
  ips: ""

project:
  - name: infra
    sourceRepo:
      - oci://ghcr.io/traefik/helm/traefik
      - oci://quay.io/jetstack/charts/cert-manager
    includeBaseRepo: true
    dest:
      - server: "https://kubernetes.default.svc"
        namespace: "*"
    clusterResourceWhitelist:
      - group: ""
        kind: "Namespace"
      - group: "rbac.authorization.k8s.io"
        kind: "CustomResourceDefinition"
