ingress:
  enabled: true
  project: infra

auth:
  enabled: true
  project: infra

vault:
  enabled: true
  project: infra

storage:
  local:
    enabled: true
  main:
    enabled: true
    project: infra

vpn:
  enabled: true
  project: infra

hook:
  enabled: true
  project: infra

repo: ""
branch: ""

traefik:
  ips: ""

project:
  - name: infra
    sourceRepo:
      - oci://ghcr.io/traefik/helm/traefik
      - oci://quay.io/jetstack/charts/cert-manager
      - oci://ghcr.io/bank-vaults/helm-charts/vault-operator
      - oci://quay.io/jetstack/charts/trust-manager
      - https://ghcr.io/external-secrets/charts
      - https://ghcr.io/bank-vaults/helm-charts
      - https://charts.zitadel.com
      - https://charts.dexidp.io
      - https://kyverno.github.io/kyverno/
      - https://charts.longhorn.io
    includeBaseRepo: true
    dest:
      - server: "https://kubernetes.default.svc"
        namespace: "*"
    clusterResourceWhitelist:
      - group: ""
        kind: "Namespace"
      - group: "apiextensions.k8s.io"
        kind: "CustomResourceDefinition"
      - group: "rbac.authorization.k8s.io"
        kind: "ClusterRole"
      - group: "rbac.authorization.k8s.io"
        kind: "Role"
      - group: "rbac.authorization.k8s.io"
        kind: "ClusterRoleBinding"
      - group: "rbac.authorization.k8s.io"
        kind: "RoleBinding"
      - group: "networking.k8s.io"
        kind: "IngressClass"
      - group: "admissionregistration.k8s.io"
        kind: "ValidatingWebhookConfiguration"
      - group: "admissionregistration.k8s.io"
        kind: "MutatingWebhookConfiguration"
      - group: "cert-manager.io"
        kind: "ClusterIssuer"
      - group: "vault.banzaicloud.com"
        kind: "Vault"
      - group: "trust.cert-manager.io"
        kind: "Bundle"
      - group: "cert-manager.io"
        kind: "Certificate"
      - group: "policies.kyverno.io"
        kind: "MutatingPolicy"
      - group: "kyverno.io"
        kind: "ClusterPolicy"
      - group: "scheduling.k8s.io"
        kind: "PriorityClass"
