name: Update version
on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".updatecli/**"
      - "updatecli-compose.yaml"
      - "**/go.mod"
      - "**/package.json"
      - "2.argo/**/Chart.yaml"
      - "2.argo/**/values.yaml"
      - ".forgejo/workflows/updatecli.yml"
permissions:
  contents: write
  pull-requests: write
jobs:
  updatecli:
    runs-on: kubernetes
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Updatecli
        uses: https://github.com/updatecli/updatecli-action@5bda7da77bf4d181bce5f807d73d832b62062acf # v3.3.0
      - name: Setup Go
        uses: https://github.com/actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "stable"
      - name: Run Updatecli
        run: updatecli compose apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
