apiVersion: v1
kind: ConfigMap
metadata:
  name: zone-map
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.zone }}
  {{ $key }}: |
    {{- $value.file | nindent 4}}
  {{- end}}
