apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.17.2
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: true
        prometheus:
          enabled: false
          servicemonitor:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
