apiVersion: v1
kind: Pod
metadata:
  name: hello-there
  labels:
    name: hello-there
spec:
  containers:
  - name: hello-there
    image: "traefik/whoami"
    resources:
      limits:
        memory: "64Mi"
        cpu: "20m"
    ports:
    - containerPort: 80
