apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mono-node
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    name: 'mono-node'
  - namespace: '*'
    name: 'in-cluster'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
