apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-instance
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: capi.argo/infra/vault
    repoURL: https://github.com/batleforc/weebo-si.git
    targetRevision: HEAD
