{{- if .Values.cilium.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-cilium
  namespace: argocd
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-argo
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: kube-system
    name: {{ .Release.Name }}
  project: {{ .Release.Name }}
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: {{ .Values.cilium.version }}
    helm:
      releaseName: cilium
      valuesObject:
        rollOutCiliumPods: true
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
        operator:
          replicas: {{ .Values.cluster.controlPlane.replicas}}
        ipam:
          mode: kubernetes
        bpf:
          masquerade: true
        forwardKubeDNSToHost: false
        kubeProxyReplacement: true
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
            cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        k8sServiceHost: "localhost"
        k8sServicePort: 7445
        ipv4:
          enabled: {{ .Values.cilium.ipv4 }}
        ipv6:
          enabled: {{ .Values.cilium.ipv6 }}
        k8s:
          requireIPv4PodCIDR: {{ .Values.cilium.ipv4 }}
          requireIPv6PodCIDR: {{ .Values.cilium.ipv6 }}
        commonLabels:
          pod-security.kubernetes.io/enforce: privileged
  ignoreDifferences:
  - kind: Secret
    name: hubble-server-certs
    jsonPointers:
    - /data/ca.crt
    - /data/tls.crt
    - /data/tls.key
  - kind: Secret
    name: cilium-ca
    jsonPointers:
    - /data/ca.crt
    - /data/ca.key
  - kind: Secret
    name: hubble-relay-client-certs
    jsonPointers:
    - /data/ca.crt
    - /data/tls.crt
    - /data/tls.key

{{- end -}}