zone:
  "db.weebo.poc.":
    zone: "weebo.poc"
    file: |
      $TTL 60 ;
      weebo.poc       IN      SOA     weebo.poc. root.weebo.poc. (
                              10; serial
                              60; refresh
                              60; retry
                              60; expire
                              60 ) ; minimum
              IN      NS      ns.weebo.poc.
      ns              A       192.168.100.11

forwarders:
- 8.8.8.8
- 1.1.1.1

bind9Version: 9.18-22.04_beta
