zone:
  "db.weebo.":
    zone: "weebo."
    file: |
      $TTL 1h ;
      $ORIGIN weebo.
      @       IN      SOA     weebo. root.weebo. (
                              10; serial
                              60; refresh
                              60; retry
                              60; expire
                              60 ) ; minimum
              IN      NS      ns.weebo.
      ns              A       192.168.100.11
      capi            A       192.168.100.11
      *.capi          A       192.168.100.11
      main            A       192.168.100.20
      *.main          A       192.168.100.20

forwarders:
- 8.8.8.8
- 1.1.1.1

bind9Version: 9.18-22.04_beta
