{{ if .Values.coroot.enabled }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-che-cluster
  namespace: coroot
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: coroot-store
      kind: SecretStore
  selector:
    secret:
      name: che-cluster-api-key
  data:
    - match:
        secretKey: api-key
        remoteRef:
          remoteKey: mc-authentik/che-cluster/coroot/monitoring
          property: api-key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-otel-collector
  namespace: coroot
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: coroot-store
      kind: SecretStore
  selector:
    secret:
      name: otel-collector-api-key
  data:
    - match:
        secretKey: api-key
        remoteRef:
          remoteKey: mc-authentik/otel-collector/monitoring
          property: api-key
{{ end }}