{{- if .Values.s3.enabled -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-cred
  namespace: {{ $.Values.s3.namespace }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: cred-store
  target:
    name: main-cred
  data:
  - secretKey: accesskey
    remoteRef:
      key: mv/s3/s3
      property: accesskey
  - secretKey: secretkey
    remoteRef:
      key: mv/s3/s3
      property: secretkey
{{- range .Values.s3.mainInstance.creds -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-cred
  namespace: {{ $.Values.s3.namespace }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: cred-store
  target:
    name: {{ .name }}-cred
  data:
  - secretKey: accesskey
    remoteRef:
      key: mv/{{ .name }}/s3
      property: accesskey
  - secretKey: secretkey
    remoteRef:
      key: mv/{{ .name }}/s3
      property: secretkey
{{- end -}}
{{- end -}}