## Sync job that wait for ExternalSecret to be created and apply the manifest in it
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-apply-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
        - name: apply-secret
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              while ! kubectl get secret {{ .Release.Name }}-auth-patch -n {{ .Release.Namespace }}; do
                echo "Waiting for secret to be created..."
                sleep 5
              done
              kubectl get secret {{ .Release.Name }}-auth-patch -n {{ .Release.Namespace }} -o=jsonpath='{.data.talos\.yaml}'| base64 -d | kubectl apply -f -
      restartPolicy: Never