apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clichouse-admin-secret
  namespace: cert-manager
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: monitoring-store
  target:
    name: clichouse-admin-secret
  data:
  - secretKey: password
    remoteRef:
      key: mv/monitoring/config
      property: CLICKHOUSE_ADMIN_PASSWORD