{{- if .Values.clickstack.enabled -}}
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: cs-clickhouse
  namespace: {{ .Release.Namespace }}
spec:
  clusterDef: clickhouse
  terminationPolicy: Delete
  topology: standalone # or cluster
  shardings:
    - name: clickhouse
      shards: 1
      template:
        replicas: 1
        systemAccounts:
          - name: admin
            secretRef:
              name: clichouse-admin-secret
              namespace: {{ .Release.Namespace }}
          - name: app
            secretRef:
              name: clichouse-app-secret
              namespace: {{ .Release.Namespace }}
          - name: otel
            secretRef:
              name: clichouse-otel-secret
              namespace: {{ .Release.Namespace }}
        volumeClaimTemplates:
          - name: data
            spec:
              # specify storage class name supports Volume Expansion
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
{{- end -}}