{{- if .Values.clickstack.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickstack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    repoURL: '{{ .Values.repo }}'
    path: '2.helm/clickstack'
    targetRevision: '{{ .Values.branch }}'
    helm:
      releaseName: clickstack
      valuesObject:
        fullnameOverride: clickstack
        hyperdx:
          existingSecret: true
          secrets: {}
          deployment:
            useExistingConfigSecret: true
            existingConfigSecret: clickstack-hyperdx-config
            existingConfigConnectionsKey: connections.json
            existingConfigSourcesKey: sources.json
        clickhouse:
          cluster:
            spec:
              # settings:
              #   defaultUserPassword:
              #     passwordType: password
              #     secret:
              #       name: clickstack-secret
              #       key: CLICKHOUSE_ADMIN_PASSWORD
              containerTemplate:
                resources:
                  requests:
                    memory: "1Gi"
                  limits:
                    memory: "2Gi"
                env:
                  - name: CLICKHOUSE_ADMIN_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: clickstack-secret
                        key: CLICKHOUSE_ADMIN_PASSWORD
                volumeMounts:
                  - name: clickhouse-users-config
                    mountPath: /etc/clickhouse-server/users.d/
                    readOnly: true
              podTemplate:
                volumes:
                  - name: clickhouse-users-config
                    secret:
                      secretName: clickstack-clickhouse-users
        mongodb:
          spec:
            members: 1
            type: ReplicaSet
            security:
              authentication:
                modes: ["SCRAM"]
            users:
              - name: hyperdx
                db: hyperdx
                passwordSecretRef:
                  name: clickstack-mongo-password
                roles:
                  - name: dbOwner
                    db: hyperdx
                  - name: clusterMonitor
                    db: admin
                scramCredentialsSecretName: clickstack-mongodb-scram
            additionalMongodConfig:
              storage.wiredTiger.engineConfig.journalCompressor: zlib
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: '{{ .Release.Namespace }}'
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
{{- end -}}
