{{- if .Values.clickstack.enabled -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clichouse-admin-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: monitoring-store
  target:
    name: clichouse-admin-secret
  data:
  - secretKey: password
    remoteRef:
      key: mv/monitoring/config
      property: CLICKHOUSE_ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clichouse-app-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: monitoring-store
  target:
    name: clichouse-app-secret
  data:
  - secretKey: password
    remoteRef:
      key: mv/monitoring/config
      property: CLICKHOUSE_APP_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clichouse-otel-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: monitoring-store
  target:
    name: clichouse-otel-secret
  data:
  - secretKey: password
    remoteRef:
      key: mv/monitoring/config
      property: CLICKHOUSE_OTEL_PASSWORD

{{- end -}}