{{- if .Values.clickstack.enabled -}}
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: cs-mongodb
  namespace: {{ .Release.Namespace }}
spec:
  terminationPolicy: Delete
  clusterDef: mongodb
  topology: replicaset
  componentSpecs:
    - name: mongodb
      replicas: 1
{{- end -}}