apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cred-store
  namespace: {{ .Values.s3.namespace }}
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    vault:
      server: "https://openbao.vault:8200"
      path: "mv"
      caProvider:
        type: Secret
        name: openbao-tls
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "s3"
          serviceAccountRef:
            name: "default"