{{ if .Values.coroot.enabled }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-clickhouse
  namespace: coroot
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: coroot-store
      kind: SecretStore
  selector:
    secret:
      name: coroot-clickhouse
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: grafana/monitoring
          property: password
{{ end }}