{{- if .Values.kubeblock.enabled -}}
{{- range .Values.kubeblock.addons }}
{{- if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeblock-{{ .name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.project }}
  syncPolicy:
    automated: {}
  source:
    chart: {{ .name }}
    repoURL: https://apecloud.github.io/helm-charts
    helm:
      releaseName: kubeblock
      valuesObject:
        image:
          registry: docker.io
        dataProtection:
          image:
            registry: docker.io
        addonChartsImage:
          registry: docker.io
  destination:
    name: "in-cluster"
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}