repo: ""
branch: ""
project: ""

clickhouseOperator:
  enabled: true
  repoURL: oci://ghcr.io/clickhouse/clickhouse-operator-helm
  chart: clickhouse-operator-helm
  # renovate: datasource=docker depName=ghcr.io/clickhouse/clickhouse-operator-helm
  version: 0.0.6

mongodbOperator:
  enabled: true
  repoURL: https://mongodb.github.io/helm-charts
  chart: mongodb-kubernetes
  # renovate: datasource=helm depName=mongodb-kubernetes registryUrl=https://mongodb.github.io/helm-charts
  version: 1.9.1

cnpgOperator:
  enabled: true
  repoURL: https://cloudnative-pg.github.io/charts
  # renovate: datasource=helm depName=cloudnative-pg registryUrl=https://cloudnative-pg.github.io/charts
  version: 0.29.0

s3Operator:
  enabled: true
  repoUrl: https://operator.rustfs.com
  chart: rustfs-operator
  # renovate: datasource=helm depName=s3-operator registryUrl=https://operator.rustfs.com
  version: 0.0.6
  namespace: s3
