repo: ""
branch: ""
project: ""

kubeblock:
  enabled: false
  crd_version: v1.0.2
  version: 1.0.2
  addons:
    - name: clickhouse
      enabled: false
      version: 1.0.3

clickhouseOperator:
  enabled: true
  repoURL: oci://ghcr.io/clickhouse
  chart: clickhouse-operator-helm
  version: 0.0.2

mongodbOperator:
  enabled: true
  repoURL: https://mongodb.github.io/helm-charts
  chart: mongodb-kubernetes
  version: 1.7.0
