apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: terra-netbird
namespace: netbird

generatorOptions:
  disableNameSuffixHash: true

resources:
  - job.yaml
  - volume.yaml


configMapGenerator:
  - name: terra-netbird-config
    namespace: netbird
    files:
      - ./terra-map/main.tf
      - ./terra-map/group.tf
      - ./terra-map/kubernetes-peer.tf
      - ./terra-map/dns.tf
