apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: capi-record
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  endpoints:
  - dnsName: capi.weebo.poc
    recordTTL: 60
    recordType: A
    targets:
    - 192.168.100.11
  - dnsName: "*.capi.weebo.poc"
    recordTTL: 60
    recordType: A
    targets:
    - 192.168.100.11
