---
- name: "Setup Proxmox"
  hosts: proxmox
  tasks:
    - name: "Update and upgrade apt packages"
      ansible.builtin.apt:
        update_cache: "yes"
        upgrade: "yes"
    - name: "Install packages"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - git
        - vim
    - name: Install and configure Wireguard
      ansible.builtin.include_role:
        name: wireguard
    - name: "Create user used for the rest"
      ansible.builtin.include_role:
        name: user
