kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "terra-job-authentik"
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi