apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: cluster-api-operator
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
    targetRevision: 0.20.0
    helm:
      releaseName: cluster-operator
      valuesObject:
        core:
          cluster-api:
            version: v1.10.4
        infrastructure:
          proxmox:
            version: v0.7.1
        controlPlane:
          talos:
            version: v0.5.10
        bootstrap:
          talos:
            version: v0.6.9
        ipam:
          in-cluster:
            version: v1.0.2
        addon:
          helm:
            version: v0.3.2
        configSecret:
          name: "infra-provider"
          namespace: "cluster-api"
        cert-manager:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cluster-api-operator-system
