apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: cluster-api-operator
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
    targetRevision: 0.19.0
    helm:
      releaseName: cluster-operator
      valuesObject:
        core: cluster-api:v1.10.1
        infrastructure: proxmox:v0.7.0
        controlPlane: talos:v0.5.10
        bootstrap: talos:v0.6.7
        ipam: in-cluster:v1.0.1
        addon: helm:v0.3.1
        configSecret:
          name: "infra-provider"
          namespace: "cluster-api"
        cert-manager:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cluster-api-operator-system
