## Sync job that wait for ExternalSecret to be created and apply the manifest in it
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-apply-secret
  namespace: eclipse-che
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
        - name: apply-secret
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              while ! kubectl get secret che-cluster -n eclipse-che; do
                echo "Waiting for secret to be created..."
                sleep 5
              done
              kubectl get secret che-cluster -n eclipse-che -o=jsonpath='{.data.che-cluster\.yaml}'| base64 -d | kubectl apply -f -
      restartPolicy: Never