apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: "che-cluster-store"
  namespace: "eclipse-che"
  annotations:
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    vault:
      server: "https://vault.weebo.poc"
      path: "mc-authentik"
      caProvider:
        type: Secret
        name: weebo.poc
        key: main-ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "auth-reader-che-cluster"
          serviceAccountRef:
            name: "default"
