apiVersion: batch/v1
kind: Job
metadata:
  name: "terra-job-authentik"
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 5
  template:
    metadata:
      annotations:
        inject-certs: "enabled"
        vault.security.banzaicloud.io/vault-addr: "https://vault.capi.weebo.poc"
        vault.security.banzaicloud.io/vault-role: "auth"
        vault.security.banzaicloud.io/vault-path: "main-cluster"
        vault.security.banzaicloud.io/vault-tls-secret: ""
    spec:
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - '-c'
        - |
          set -x
          cd /terraform
          touch anotherNameThatSoundNothing.tf
          rm -rf *.tf
          cp /scripts/*.tf .
          terraform init --upgrade
          terraform apply -auto-approve
        volumeMounts:
        - mountPath: terraform
          name: terra-job
        - mountPath: /scripts
          name: "script-vol"
      restartPolicy: Never
      volumes:
      - name: "script-vol"
        configMap:
          name: "terra-auth-config"
      - name: terra-job
        persistentVolumeClaim:
          claimName: "terra-job-authentik"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "terra-job-authentik-empty"
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: create-in-vault
        image: hashicorp/terraform:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - '-c'
        - |
          set -x
          echo "WIP"
        volumeMounts:
        - mountPath: terraform
          name: terra-job
      restartPolicy: Never
      volumes:
      - name: terra-job
        persistentVolumeClaim:
          claimName: "terra-job-authentik"