apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: terra-auth
namespace: authentik

generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
  - name: terra-auth-config
    namespace: authentik
    files:
      - ./main.tf
      - ./group.tf
      - ./user.tf
