{{- if .Values.storage.longhorn.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-longhorn-ingress
  namespace: longhorn-system
  annotations:
    cert-manager.io/cluster-issuer: "vault-issuer"
    cert-manager.io/common-name: "longhorn.{{ .Values.release }}.{{.Values.dns.base}}"
    cert-manager.io/subject-organizations: "WeeboSI"
    cert-manager.io/subject-organizationalunits: "{{ .Release.Name }}"
    cert-manager.io/subject-countries: "FR"
    cert-manager.io/subject-localities: "{{ .Release.Name }}"
    cert-manager.io/subject-provinces: "Proxmox"
spec:
  tls:
  - hosts:
    - "longhorn.{{ .Values.release }}.{{.Values.dns.base}}"
    secretName: longhorn-ingress-tls
  rules:
  - host: "longhorn.{{ .Values.release }}.{{.Values.dns.base}}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
{{- end -}}