apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: mono-node-proxmox-cluster
  namespace: default
spec:
  scheduleHints:
    memoryAdjustment: 0
  allowedNodes:
  - weebo4
  controlPlaneEndpoint:
    host: 192.168.100.20
    port: 6443
  dnsServers:
  - 8.8.8.8
  - 8.8.4.4
  ipv4Config:
    addresses:
    - 192.168.100.21-192.168.100.30
    gateway: 192.168.100.1
    prefix: 20
