apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: HostSNI("vault.weebo.poc")
      services:
        - name: vault
          port: 8200
  tls:
    passthrough: true
