apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terra-vault
  namespace: argocd
spec:
  project: default
  source:
    path: all-in-one.argo/terra/vault
    repoURL: "https://github.com/batleforc/weebo-si"
    targetRevision: HEAD
  destination:
    namespace: vault
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
