{{- if .Values.che.cheApp.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: che-app-bis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: "{{ .Values.project }}"
  source:
    repoURL: '{{ .Values.repo }}'
    targetRevision: '{{ .Values.branch }}'
    path: '2.argo/helm/che/sub-bis'
    helm:
      releaseName: che-app
      valuesObject:
        {{- with .Values }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'argocd'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
{{- end -}}
