{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
  namespace: argocd
  annotations:
    sync-waves.argoproj.io/sync-wave: "5"
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: auth
  target:
    name: argo-dev-auth
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        url: '{{ printf "{{"}} .url }}'
        client_id: '{{ printf "{{"}} .client_id }}'
        client_secret: '{{ printf "{{"}} .client_secret }}'
  data:
    - secretKey: url
      remoteRef:
        key: mc-authentik/argocd-client/auth
        property: AUTHENTIK_URL
    - secretKey: client_id
      remoteRef:
        key: mc-authentik/argocd-client/auth
        property: AUTHENTIK_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: mc-authentik/argocd-client/auth
        property: AUTHENTIK_CLIENT_SECRET
{{- end -}}