apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: outbound
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acme:
    email: maxleriche.60@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: weebo-outbound-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
