apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - match: HostSNI(`vault.capi.weebo.poc`) || Host('vault.capi.weebo.poc')
    kind: Rule
    services:
    - name: vault
      port: 8200
  tls:
    passthrough: true
