apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/weebo.poc
    server: https://vault.capi.weebo.poc
    caBundleSecretRef:
      key: ca.crt
      name: vault-tls
    auth:
      kubernetes:
        role: vault-issuer
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer
          namespace: cert-manager
