{{- if .Values.externalSecrets.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  source:
    chart: external-secrets
    repoURL: ghcr.io/external-secrets/charts
    targetRevision: {{ .Values.externalSecrets.version }}
    helm:
      releaseName: external-secrets
  destination:
    name: "in-cluster"
    namespace: external-secrets
{{- end -}}