apiVersion: v1
kind: ConfigMap
metadata:
  name: named-map
  namespace: {{ .Release.Namespace }}
data:
  named.conf: |
    include "/val/lib/bind/pri/tsig.key";
    tls local-tls {
      key-file "/var/lib/bind/pri/ns.4.weebo.fr/tls.key";
      cert-file "/var/lib/bind/pri/ns.4.weebo.fr/tls.crt";
    };
    options {
      directory "/var/cache/bind";
      querylog yes;
      listen-on port 53 { any; };
      listen-on-v6 port 53 { any; };
      listen-on port 443 tls local-tls http default {any;};
      listen-on-v6 port 443 tls local-tls http default {any;};
      allow-query { any; };
      forwarders {
        {{ range .Values.forwarders }}
        {{ . }};
        {{ end }}
      };
      dnssec-validation no; # TODO: change moi çaaaa ! CACAAAA
    };
    {{ range $key, $value := .Values.zone }}
    zone "{{ $value.zone }}" {
      type primary;
      file "/var/lib/bind/pri/{{$value.zone}}/{{ $key}}";
      allow-transfer {
        key "tsig-key";
      };
      update-policy {
        grant tsig-key zonesub ANY;
      };
    };
    {{ end }}
