apiVersion: v1
kind: Service
metadata:
  name: dns-server-in
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: dns-server
  annotations:
    {{ toYaml .Values.annotations | nindent 4 }}
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: loop
      protocol: TCP
      port: 953
      targetPort: 953
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: tls
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: dns-server
  type: ClusterIP
  clusterIP: 10.96.0.11