{{ if .Values.coroot.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: monitoring
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: "grafana"
    targetRevision: {{ .Values.grafana.version }}
    helm:
      releaseName: grafana
      valuesObject:
        sidecar:
          alerts:
            enabled: true
          notifiers:
            enabled: true
          dashboards:
            enabled: true
          datasources:
            enabled: true
  destination:
    name: in-cluster
    namespace: 'grafana'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{ end }}