{{ if .Values.grafana.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-auth
  namespace: grafana
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: grafana-store
  target:
    name: grafana-auth
  data:
    - secretKey: client_id
      remoteRef:
        key: mc-authentik/grafana/auth
        property: AUTHENTIK_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: mc-authentik/grafana/auth
        property: AUTHENTIK_CLIENT_SECRET
    - secretKey: url
      remoteRef:
        key: mc-authentik/grafana/auth
        property: AUTHENTIK_URL
{{ end }}