apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-cluster-obj
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: {{ .Release.Name }}
  source:
    repoURL: 'https://github.com/batleforc/weebo-si'
    path: 'all-in-one.argo/helm/cluster-tpl-object'
    helm:
      releaseName: {{ .Release.Name }}-cluster-obj
      valuesObject:
        {{ range $key, $value := .Values }}
        {{ $key }}: {{ $value | toJson | indent 8 }}
        {{- end }}
        release: {{ .Release.Name }}
  destination:
    name: {{ .Release.Name }}
    namespace: 'default'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m