apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance-{{ .Release.Name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/batleforc/weebo-si'
    path: 'all-in-one.argo/helm/glance'
    helm:
      releaseName: glance
      valuesObject:
        ingress:
          secure: false
          insecure: "Path(`/`)"
  destination:
    name: {{ .Release.Name }}
    namespace: 'glance'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
