apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Release.Namespace }}"
  annotations:
    weebo.si/dyn-cluster: "{{ .Release.Name }}"
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
