apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "glance"
  namespace: "glance"
spec:
  commonName: "glance.4.weebo.fr"
  secretName: "glance-certificate"
  dnsNames:
    - "glance.4.weebo.fr"
  issuerRef:
    kind: ClusterIssuer
    name: "outbound"
