apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance
  namespace: glance
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`glance.4.weebo.fr`)
      priority: 10
      services:
        - name: internal
          namespace: glance
          passHostHeader: true
          port: 8080
      middlewares:
        - name: vpn-only
          namespace: traefik
        - name: authentik
          namespace: authentik
    - kind: Rule
      match: Host(`glance.4.weebo.fr`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - name: authentik-server
          namespace: authentik-server
          port: 80
          passHostHeader: true
      middlewares:
        - name: vpn-only
          namespace: traefik
  tls:
    secretName: glance-certificate
