apiVersion: v2
name: coturn-app
type: application

version: 9.1.0

# renovate: image=coturn/coturn
appVersion: 4.7.0

dependencies:
  - name: postgresql
    version: 16.7.10
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: mysql
    version: 13.0.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mysql.enabled