version:
  helm: 0.0.10
  app: "v0.8.4"

repo: glanceapp/glance

pullPolicy: Always

content: |
  pages:
    - name: Startpage
      width: slim
      hide-desktop-navigation: true
      center-vertically: true
      columns:
        - size: full
          widgets:
            - type: search
              autofocus: true

            - type: monitor
              cache: 1m
              title: Services
              sites:
                - title: Netbird
                  url: https://netbird.4.weebo.fr
                  icon: si:wireguard
                - title: Authentik
                  url: https://login.4.weebo.fr/
                  icon: si:authentik
                - title: Vault
                  url: https://vault.4.weebo.fr/
                  icon: si:vault
                - title: ArgoCD
                  url: https://argo.4.weebo.fr/
                  icon: si:argo
                - title: Omni
                  url: https://omni.4.weebo.fr/
                  icon: si:talos
                - title: Traefik Dashboard
                  url: http://4.weebo.fr/dashboard/
                  icon: si:traefikproxy
                - title: Kubevirt Manager
                  url: https://kubevirt-manager.4.weebo.fr/
                  icon: mdi:server-outline

            - type: bookmarks
              groups:
                - title: General
                  links:
                    - title: Gmail
                      url: https://mail.google.com/mail/u/0/
                    - title: Amazon
                      url: https://www.amazon.com/
                    - title: Github
                      url: https://github.com/
                - title: Entertainment
                  links:
                    - title: YouTube
                      url: https://www.youtube.com/
                    - title: Prime Video
                      url: https://www.primevideo.com/
                    - title: Disney+
                      url: https://www.disneyplus.com/
                - title: Social
                  links:
                    - title: Reddit
                      url: https://www.reddit.com/
                    - title: Twitter
                      url: https://twitter.com/
                    - title: Instagram
                      url: https://www.instagram.com/