version: '3'

env:
  KUBECONFIG: "{{.ROOT_DIR}}/capi.terraform/kubeconfig"
  ARGO_APP_REPO: "https://github.com/batleforc/weebo-si"
  ARGO_APP_USERNAME: "batleforc"
  ARGO_DEST_SERVER: "https://kubernetes.default.svc"
  ARGO_VERSION: "7.8.12"

tasks:
  init-install:
    cmds:
    - kubectl apply -f ./argo/ns.yaml
    - helm repo add argo https://argoproj.github.io/argo-helm
    - helm repo update
    - helm upgrade --install argocd argo/argo-cd --namespace argocd --version $ARGO_VERSION
    - task capi:argo:login-pf
    - task capi:argo:init-private-repo
    - task capi:argo:install
  install:
    cmds:
    - helm repo update
    - helm upgrade --install argocd argo/argo-cd --namespace argocd --version $ARGO_VERSION --values ./argo/values.yaml
  port-forward:
    cmds:
    - kubectl port-forward svc/argocd-server -n argocd 8080:443
  get-pwd:
    cmds:
    - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  login-pf:
    vars:
      PASSWORD:
        sh: task argo:get-pwd
    cmds:
    - argocd login --port-forward --port-forward-namespace argocd localhost:8080 --username admin --password {{.PASSWORD}} --insecure
    - kubectl config set-context --current --namespace=argocd
  init-private-repo:
    cmds:
    - argocd repo add $ARGO_APP_REPO --username $ARGO_APP_USERNAME --password $ARGO_GITHUB_TOKEN --port-forward --port-forward-namespace argocd
  install-app:
    cmds:
    - argocd app create weebo-capi --repo $ARGO_APP_REPO --directory-recurse --path capi.argo/infra/app --dest-server $ARGO_DEST_SERVER --dest-namespace default --sync-policy automated --directory-recurse --port-forward --port-forward-namespace argocd
