dex:
  enabled: true
  version: "0.24.1"
  issuer: "dex.4.weebo.fr"
  mainConnector:
    type: oidc
    id: weebo
    name: Weebo
    config:
      issuer: "https://auth.4.weebo.fr"

repo: ""
project: ""
branch: ""
