dex:
  enabled: true
  version: "0.24.1"
  issuer: "dex.weebo.poc"
  mainConnector:
    issuer: "https://auth.batleforc.fr/application/o/lab/"
    clientID: "lab"

authentik:
  enabled: true
  version: 2026.5.3
  argoAuth:
    enabled: true

dns:
  domain: auth.weebo.poc
  certificate:
    enabled: true
    name: auth-tls
    issuerRef: "vault-issuer"
    issuerRefKind: ClusterIssuer
  createWithCRD: false
  ipv4:
    enabled: true
    addresses:
      - ""
  ipv6:
    enabled: true
    addresses:
      - ""

repo: ""
project: ""
branch: ""
