dex:
  enabled: true
  # renovate: datasource=helm depName=dex registryUrl=https://charts.dexidp.io
  version: "0.24.1"
  issuer: "dex.weebo.poc"
  mainConnector:
    issuer: "https://auth.weebo.poc/application/o/che-cluster/"
    clientID: "che-cluster"

authentik:
  enabled: true
  # renovate: datasource=helm depName=authentik registryUrl=https://charts.goauthentik.io
  version: 2026.8.0
  argoAuth:
    enabled: true

dns:
  domain: auth.weebo.poc
  certificate:
    enabled: true
    name: auth-tls
    issuerRef: "vault-issuer"
    issuerRefKind: ClusterIssuer
  createWithCRD: false
  ipv4:
    enabled: true
    addresses:
      - ""
  ipv6:
    enabled: true
    addresses:
      - ""

repo: ""
project: ""
branch: ""
