apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: ""
      server: ""
    name: Weebo-si
contexts:
  - context:
      cluster: Weebo-si
      user: Weebo-si
    name: Weebo-si
current-context: Weebo-si
kind: Config
preferences: {}
users:
  - name: Weebo-si
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://dex.weebo.poc
          - --oidc-client-id=weebo-kube
          - --oidc-client-secret=
          - --oidc-extra-scope="email offline_access profile openid groups"
          - --grant-type=authcode
        command: kubectl
        env: null
        provideClusterInfo: false
