apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openunison-login
  namespace: argocd
spec:
  destination:
    namespace: open-unison
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/1/clientConfig/caBundle
    - /webhooks/2/clientConfig/caBundle
    - /webhooks/3/clientConfig/caBundle
    - /webhooks/4/clientConfig/caBundle
    kind: ValidatingWebhookConfiguration
  project: default
  sources:
  - chart: openunison-operator
    helm:
      releaseName: openunison
      valueFiles:
      - $values/capi.argo/infra/open-unison/val/values.yaml
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 3.0.18

  - chart: orchestra
    helm:
      releaseName: orchestra
      valueFiles:
      - $values/capi.argo/infra/open-unison/val/values.yaml
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 3.1.17

  - chart: orchestra-login-portal
    helm:
      releaseName: orchestra-login-portal
      valueFiles:
      - $values/capi.argo/infra/open-unison/val/values.yaml
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 2.3.71

  - repoURL: https://github.com/batleforc/weebo-si.git
    path: capi.argo/infra/open-unison/val/
  - ref: values
    repoURL: https://github.com/batleforc/weebo-si.git
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
