# The OIDC client secret of the `endpoint-gateway` Authentik application.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.clientSecret.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: weebo-si-hardening-vault
  target:
    name: {{ .Values.clientSecret.name }}
  data:
    - secretKey: {{ .Values.clientSecret.key }}
      remoteRef:
        key: {{ .Values.clientSecret.vaultKey }}
        property: {{ .Values.clientSecret.vaultProperty }}
