{{- if or (gt (int .Values.cluster.worker.replicas) 0) .Values.cluster.worker.autoscale -}}
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: "{{ .Release.Name }}-infra-worker"
spec:
  template:
    spec:
      generateType: join
      talosVersion: {{ .Values.cluster.talosVersion }}
      strategicPatches:
        - |
          - op: replace
            path: /machine/install
            value:
              extensions:
                - image: {{ .Values.cluster.talos.qemuGuestAgent.image }}
          - op: replace
            path: /machine/network/nameservers
            value:
              - 10.96.0.11
          - op: add
            path: /machine/install/extraKernelArgs
            value:
              - net.ifnames=0
          - op: add
            path: /machine/install/image
            value: {{ .Values.cluster.talos.installImage }}
          - op: add
            path: /machine/sysctls
            value:
              net.ipv4.ip_forward: 1
              net.ipv6.conf.all.forwarding: 1
              vm.nr_hugepages: 2048
          - op: add
            path: /machine/kubelet/extraMounts
            value: []
          {{ if .Values.storage.local.enabled -}}
          - op: add
            path: /machine/kubelet/extraMounts/-
            value:
              source: /var/local-path-provisioner
              destination: /var/local-path-provisioner
              type: bind
              options:
                - bind
                - rshared
                - rw
          {{- end }}
          {{ if .Values.storage.longhorn.enabled -}}
          - op: add
            path: /machine/kubelet/extraMounts/-
            value:
              source: /var/lib/longhorn
              destination: /var/lib/longhorn
              type: bind
              options:
                - bind
                - rshared
                - rw
          - op: add
            path: /machine/kernel
            value:
              modules:
                - name: nvme_tcp
                - name: vfio_pci
          {{- end }}
{{- end -}}