{{- if and (and (not .Values.vpn.enabled) (not .Values.externalSecrets.enabled)) (or (gt (int .Values.cluster.worker.replicas) 0) .Values.cluster.worker.autoscale) -}}
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: "{{ .Release.Name }}-infra-worker"
spec:
  template:
    spec:
      generateType: join
      talosVersion: {{ .Values.cluster.talosVersion }}
      strategicPatches:
        - |
          - op: replace
            path: /machine/features/hostDNS/forwardKubeDNSToHost
            value: false
          - op: add
            path: /machine/install/extraKernelArgs
            value:
              - net.ifnames=0
          - op: add
            path: /machine/install/image
            value: {{ .Values.cluster.talos.installImage }}
          - op: add
            path: /machine/sysctls
            value:
              net.ipv4.ip_forward: 1
              net.ipv6.conf.all.forwarding: 1
              vm.nr_hugepages: 2048
          - op: replace
            path: /machine/features/hostDNS/forwardKubeDNSToHost
            value: false
          {{ if .Values.cilium.enabled -}}
          - op: add
            path: /cluster/network/cni
            value:
              name: none
          - op: add
            path: /cluster/proxy
            value:
              disabled: true
          - op: replace
            path: /cluster/network/podSubnets
            value:
              {{- range $index, $subnet := .Values.cluster.network.podsCidr }}
              - {{ $subnet }}
              {{- end }}
          - op: replace
            path: /cluster/network/serviceSubnets
            value:
              {{- range $index, $subnet := .Values.cluster.network.servicesCidr }}
              - {{ $subnet }}
              {{- end }}
          {{- end }}
{{- end -}}