apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: "{{ .Release.Name }}-infra"
  namespace: "{{ .Release.Namespace }}"
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: none
      virtualMachineTemplate:
        metadata:
          namespace: "{{ .Release.Namespace }}"
        spec:
          dataVolumeTemplates:
            - metadata:
                name: "boot-volume"
              spec:
                pvc:
                  volumeMode: Filesystem
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: "{{ .Values.cluster.controlPlane.storage }}"
                source:
                  {{ if eq .Values.cluster.kubevirt.source "registry" }}
                  registry:
                    url: "{{ .Values.cluster.kubevirt.talosQcow2 }}"
                    secretRef: "{{ .Release.Name }}-cdiregistry"
                  {{ else }}
                  http:
                    url: "{{ .Values.cluster.kubevirt.talosQcow2 }}"
                  {{ end }}
                    # namespace: golden-images
          runStrategy: Always
          template:
            spec:
              domain:
                resources:
                  requests:
                    memory: {{ .Values.cluster.controlPlane.ram }}
                cpu:
                  cores: {{ .Values.cluster.controlPlane.cpu.cores }}
                  threads: {{ .Values.cluster.controlPlane.cpu.threads }}
                devices:
                  networkInterfaceMultiqueue: true
                  disks:
                    - disk:
                        bus: virtio
                      name: dv-volume
              evictionStrategy: External
              volumes:
                # - name: serviceaccount
                #   serviceAccount:
                #     serviceAccountName: cdi-cloner
                - dataVolume:
                    name: "boot-volume"
                  name: dv-volume
