apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: "{{ .Release.Name }}-infra"
  namespace: "{{ .Release.Namespace }}"
spec:
  controlPlaneServiceTemplate:
    spec:
      type: ClusterIP
