bankVault:
  enabled: true
  ns: vault-operator
  version: 1.24.0

externalSecrets:
  enabled: true
  version: "2.2.0"

vaultApp:
  enabled: true

vaultInstance:
  enabled: true
  version: "2.0.2"
  image: hashicorp/vault
  hook:
    enabled: true
    version: 1.23.1
  dns: vault.4.weebo.fr

repo: ""
project: ""
branch: ""
