{{- if and .Values.batlehub.enabled .Values.batlehub.valkey.enabled -}}
apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  name: batlehub-valkey
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shards: {{ .Values.batlehub.valkey.shards }}
  replicas: {{ .Values.batlehub.valkey.replicas }}
  podDisruptionBudget:
    mode: Disabled
  persistence:
    size: {{ .Values.batlehub.valkey.storage.size }}
    storageClassName: {{ .Values.batlehub.valkey.storage.storageClassName }}
  users:
    - name: batlehub
      passwordSecret:
        name: batlehub-valkey-cred
        keys: [pwd]
      permissions: "+@all ~* &*"
{{- end -}}
