version: "3"

tasks:
  base:
    dir: ./1.pulu-conf
    env:
      PULUMI_CONFIG_PASSPHRASE: ""
      KUBECONFIG: ../0.config/kubeconfig.yaml
      ARGO_DNS: "argo.weebo.poc"
      GIT_REPO: "https://git.batleforc.fr/batleforc/weebo-si"
      GIT_BRANCH: "develop"
    cmds:
      - pulumi {{ .CLI_ARGS }}
  up:
    desc: "Update the infrastructure by running pulumi up"
    cmds:
      - task puluconf:base -- up
