apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: terra-auth
namespace: authentik

generatorOptions:
  disableNameSuffixHash: true

resources:
  - job.yaml
  - volume.yaml


configMapGenerator:
  - name: terra-auth-config
    namespace: authentik
    files:
      - ./terra-map/main.tf
      - ./terra-map/data.tf
      - ./terra-map/group.tf
      - ./terra-map/user.tf
      - ./terra-map/argo-main-cluster.tf
      - ./terra-map/net-bird.tf
      - ./terra-map/flow.tf
      - ./terra-map/omni.tf
      - ./terra-map/kubevirt-manager.tf
      - ./terra-map/outpost.tf
      - ./terra-map/glance.tf
      - ./terra-map/che-cluster.tf
      - ./terra-map/grafana.tf
      - ./terra-map/harbor.tf
