# Create a config map with a single script mean to generate a kubeconfig file
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-maker
  namespace: kubevirt-omni
data:
  makeKubeconfig.sh: |
    #!/bin/sh
    ca=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 -w0)
    token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token | base64 -w0)
    namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    echo "
      apiVersion: v1
      kind: Config
      clusters:
      - name: default-cluster
        cluster:
          certificate-authority-data: ${ca}
          server: ${KUBE_SERVER}
      contexts:
      - name: default-context
        context:
          cluster: default-cluster
          namespace: ${namespace}
          user: default-user
      current-context: default-context
      users:
      - name: default-user
        user:
          token: ${token}
    " > /kubeconfig/config
    chmod 644 /kubeconfig/config
    ls -l /kubeconfig/config
