---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-omni
  namespace: kubevirt-omni
---
apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-omni
  namespace: kubevirt-omni
  annotations:
    kubernetes.io/service-account.name: kubevirt-omni
type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-omni
rules:
  - apiGroups:
      - cdi.kubevirt.io
    resources:
      - datavolumes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-omni
subjects:
  - kind: ServiceAccount
    name: kubevirt-omni
    namespace: kubevirt-omni
roleRef:
  kind: ClusterRole
  name: kubevirt-omni
  apiGroup: rbac.authorization.k8s.io
