version: '3'

tasks:
  init-vpn-config:
    dir: ./0.terraform/vpn-proxmox
    cmds:
    - echo "Install packages"
    - terraform init
    - TF_VAR_dns="${PROXMOX_DNS}" terraform apply -auto-approve
  setup-proxmox:
    dir: ./0.ansible/setup-proxmox
    cmds:
    - echo "Setup Proxmox"
    - task proxmox:init-vpn-config
    - ansible-playbook -i ../inventories/inventory.proxmox.yml setup.yml --vault-password-file=../../vault_password
  change-ssh-port:
    dir: ./0.ansible/setup-proxmox
    cmds:
    - echo "Change ssh port"
    - ansible-playbook -i ../inventories/inventory.proxmox.yml ssh.yml --vault-password-file=../../vault_password
  vpn-local-up:
    dir: ./0.terraform/vpn-proxmox
    cmds:
    - echo "Start VPN"
    - sudo wg-quick up ./pc1.wg.conf
  vpn-local-down:
    dir: ./0.terraform/vpn-proxmox
    cmds:
    - echo "Stop VPN"
    - sudo wg-quick down ./pc1.wg.conf
