version: '3'

tasks:
  init-vpn-config:
    dir: ./0.terraform/vpn-proxmox
    cmds:
    - echo "Install packages"
    - terraform init
    - TF_VAR_dns="${PROXMOX_DNS}" terraform apply -auto-approve
  setup-proxmox:
    dir: ./0.ansible/setup-proxmox
    cmds:
    - echo "Setup Proxmox"
    - task proxmox:init-vpn-config
    - ansible-playbook -i ../inventories/inventory.proxmox.yml setup.yml --vault-password-file=../../vault_password
  change-ssh-port:
    dir: ./0.ansible/setup-proxmox
    cmds:
    - echo "Change ssh port"
    - ansible-playbook -i ../inventories/inventory.proxmox.yml ssh.yml --vault-password-file=../../vault_password
  vpn-local-up:
    dir: ./0.terraform/vpn-proxmox
    cmds:
    - echo "Start VPN"
    - wg-quick up ./pc1.wg.conf
  vpn-local-down:
    dir: ./0.terraform/vpn-proxmox
    cmds:
    - echo "Stop VPN"
    - wg-quick down ./pc1.wg.conf
  remove-old-ssh-keys:
    cmds:
    - echo "Remove old ssh keys"
    - ssh-keygen -R "${PROXMOX_DNS}"
  restart:
    dir: ./0.terraform/restart-vm
    silent: true
    cmds:
      - echo "Start VM"
      - terraform init
      - TF_VAR_ssh_public_key="${SSH_KEY}" TF_VAR_ovh_server_name="${SERVER_NAME}" terraform apply
  install-proxmox:
    dir: ./0.terraform/install-vm-proxmox
    silent: true
    cmds:
      - echo "Install Proxmox"
      - terraform init
      - TF_VAR_ssh_public_key="${SSH_KEY}" TF_VAR_ovh_server_name="${SERVER_NAME}" terraform apply