{{ if and .Values.monitoring.enabled .Values.monitoring.coroot.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coroot-api-key
  namespace: coroot
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: coroot-store
  target:
    name: coroot-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: mc-authentik/che-cluster/coroot/monitoring
        property: api-key
{{ end }}