{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: auth
  namespace: argocd-client
  annotations:
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    vault:
      server: "https://vault.capi.weebo.poc"
      path: "mc-authentik"
      caProvider:
        type: Secret
        name: weebo.poc
        key: main-ca.crt
      auth:
        kubernetes:
          mountPath: "{{ .Values.release}}"
          role: "auth-read"
          serviceAccountRef:
            name: "default"

{{- end }}