apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete-sa-job
  namespace: "{{ .Values.cluster.namespace }}"
  annotations:
    argocd.argoproj.io/hook: PostDelete
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: delete-ressources
        command:
        - /bin/bash
        - '-c'
        - |
          set -x
          kubectl delete secret {{ .Release.Name }}-secret -n argocd
        image: quay.io/agnosticd/ee-multicloud:latest
      - name: delete-in-vault
        image: hashicorp/terraform:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - '-c'
        - |
          set -x
          cd /terraform
          touch anotherNameThatSoundNothing.tf
          rm -rf *.tf
          cp /scripts/*.tf .
          TF_VAR_cluster_name="{{ .Release.Name }}" TF_VAR_host="https://{{ tpl .Values.dns.name . }}.{{.Values.dns.base}}:6443" terraform destroy -auto-approve
        volumeMounts:
        - mountPath: /tmp
          name: temp
        - mountPath: terraform
          name: terra-job
        - mountPath: /scripts
          name: "{{ .Release.Name }}-script-vol"
        - mountPath: "/ca/vault"
          name: vault-ca
      restartPolicy: Never
      volumes:
      - name: "{{ .Release.Name }}-script-vol"
        configMap:
          name: "{{ .Release.Name }}-create-sa"
      - name: kube-secret
        secret:
          secretName: "{{ .Release.Name }}-kubeconfig"
      - name: vault-ca
        secret:
          secretName: vault-tls
      - name: terra-job
        persistentVolumeClaim:
          claimName: "create-sa-pvc-{{ .Release.Name }}"
      - name: temp
        emptyDir: {}