apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: terra-vault
namespace: vault

generatorOptions:
  disableNameSuffixHash: true

resources:
  - job.yaml
  - volume.yaml


configMapGenerator:
  - name: terra-vault-config
    namespace: vault
    files:
      - ./terra-map/main.tf
      - ./terra-map/authentik.tf
