apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.release }}
  namespace: argocd-client
  labels:
    app.kubernetes.io/name: {{ .Values.release }}-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd-client
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ .Values.release }}.argo/infra
    repoURL: https://github.com/batleforc/weebo-si
    targetRevision: HEAD
    directory:
      recurse: true