apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/default
    server: https://vault.capi.weebo.poc
    caBundleSecretRef:
      key: vault-ca.crt
      name: certificate
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/{{.Values.release}}
        secretRef:
          name: vault-issuer
          key: token
