---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd-client
  labels:
    app.kubernetes.io/name: authentik
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: authentik
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io
    targetRevision: 2025.6.4
    helm:
      releaseName: authentik
      valuesObject:
        global:
          podAnnotations:
            inject-certs: "enabled"
            vault.security.banzaicloud.io/vault-addr: "https://vault.capi.weebo.poc"
            vault.security.banzaicloud.io/vault-role: "auth"
            vault.security.banzaicloud.io/vault-path: "main-cluster"
            vault.security.banzaicloud.io/vault-tls-secret: ""
        authentik:
          bootstrap_token: "vault:mc-authentik/data/main-config#AUTHENTIK_BOOTSTRAP_TOKEN"
          bootstrap_password: "vault:mc-authentik/data/main-config#AUTHENTIK_BOOTSTRAP_PASSWORD"
          secret_key: "PleaseGenerateASecureKey"
          error_reporting:
            enabled: true
          postgresql:
            password: "ThisIsNotASecurePassword"

        server:
          ingress:
            ingressClassName: traefik
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "vault-issuer"
              cert-manager.io/common-name: "login.main-cluster.weebo.poc"
              cert-manager.io/subject-organizations: "WeeboSI"
              cert-manager.io/subject-organizationalunits: "main-cluster"
              cert-manager.io/subject-countries: "FR"
              cert-manager.io/subject-localities: "main-cluster"
              cert-manager.io/subject-provinces: "Proxmox"
            hosts:
            - login.main-cluster.weebo.poc
            https: false
            tls:
            - secretName: authentik-tls
              hosts:
              - login.main-cluster.weebo.poc
        # env:
        #   - name: AUTHENTIK_BOOTSTRAP_PASSWORD
        #     value: "vault:mc-authentik/data/main-config#AUTHENTIK_BOOTSTRAP_PASSWORD"
        #   - name: AUTHENTIK_BOOTSTRAP_EMAIL
        #     value: "vault:mc-authentik/data/main-config#AUTHENTIK_BOOTSTRAP_EMAIL"
        #   - name: AUTHENTIK_BOOTSTRAP_TOKEN
        #     value: "vault:mc-authentik/data/main-config#AUTHENTIK_BOOTSTRAP_TOKEN"

        postgresql:
          enabled: true
          auth:
            password: "ThisIsNotASecurePassword"
        redis:
          enabled: true
