apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: terra-auth
namespace: auth

generatorOptions:
  disableNameSuffixHash: true

resources:
  - job.yaml
  - volume.yaml

configMapGenerator:
  - name: terra-auth-config
    namespace: auth
    files:
      - ./terra-map/main.tf
      - ./terra-map/data.tf
      - ./terra-map/group.tf
      - ./terra-map/argo.tf
      - ./terra-map/harbor.tf
      - ./terra-map/vault.tf
      - ./terra-map/che-cluster.tf
      - ./terra-map/s3.tf
