{{- if .Values.argo.apps.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-argo-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-argo-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: argocd-client
    name: {{ .Release.Name }}
  project: {{ .Release.Name }}
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: {{ .Values.argo.apps.version }}
    helm:
      releaseName: argo-apps
      valuesObject:
        configs:
          cm:
            dex.config: |
              connectors:
                - type: oidc
                  name: Weebo-SI
                  id: weebo-si
                  config:
                    issuer: $argo-dev-auth:url
                    clientID: $argo-dev-auth:client_id
                    clientSecret: $argo-dev-auth:client_secret
                    requestedIdTokenClaims:
                      groups:
                        essential: true
                    requestedScopes:
                      - "openid"
                      - "profile"
                      - "email"
                      - "groups"
            url: "https://{{ .Values.argo.apps.prefix }}.{{ tpl .Values.dns.name . }}.{{.Values.dns.base}}"
          params:
            server.insecure: true
          rbac:
            scopes: "{{ .Values.argo.apps.rbac.scopes }}"
            policy.csv:
              {{- .Values.argo.apps.rbac.policy | toYaml | indent 14 }}
        global:
          domain: "{{ .Values.argo.apps.prefix }}.{{ tpl .Values.dns.name . }}.{{.Values.dns.base}}"
          podAnnotations:
            inject-certs: "enabled"
        server:
          ingress:
            enabled: true
            tls: true
            annotations:
              cert-manager.io/cluster-issuer: "vault-issuer"
              cert-manager.io/common-name: "{{ .Values.argo.apps.prefix }}.{{ tpl .Values.dns.name . }}.{{.Values.dns.base}}"
              cert-manager.io/subject-organizations: "WeeboSI"
              cert-manager.io/subject-organizationalunits: "{{ .Release.Name }}"
              cert-manager.io/subject-countries: "FR"
              cert-manager.io/subject-localities: "{{ .Release.Name }}"
              cert-manager.io/subject-provinces: "Proxmox"
{{- end -}}
