{{- if .Values.argo.main -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-argo
  namespace: argocd
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: {{ .Release.Name }}
  source:
    path: {{ .Release.Name }}.argo/infra
    repoURL: https://github.com/batleforc/weebo-si
    targetRevision: HEAD
    directory:
      recurse: true
{{- end -}}