apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-create-sa-job
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 100
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.capi.weebo.poc"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      containers:
      - name: create-webhook
        command:
        - /bin/bash
        - '-c'
        - |
          set -x
          ansible-playbook -i localhost /scripts/playbook.yaml
        image: quay.io/agnosticd/ee-multicloud:latest
        volumeMounts:
        - mountPath: /scripts
          name: {{ .Release.Name }}-script-vol
        - mountPath: /tokens
          name: kube-secret
        - mountPath: "/ca/vault"
          name: vault-ca
      restartPolicy: Never
      volumes:
      - name: {{ .Release.Name }}-script-vol
        configMap:
          name: {{ .Release.Name }}-create-sa
      - name: kube-secret
        secret:
          secretName: {{ .Release.Name }}-kubeconfig
      - name: vault-ca
        secret:
          secretName: vault-tls