{{- if .Values.kyverno.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-kyverno
  namespace: argocd
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-argo
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
  destination:
    namespace: kyverno
    name: {{ .Release.Name }}
  project: {{ .Release.Name }}
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: {{ .Values.kyverno.version }}
    helm:
      releaseName: kyverno
      parameters:
        - name: crds.migration.enabled
          value: 'false'

{{- end -}}