{{- if .Values.storage.longhorn.enabled }}
---
apiVersion: v1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: {{ .Release.Name }}
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: {{ .Values.storage.longhorn.version }}
    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
  destination:
    name: {{ .Release.Name }}
    namespace: longhorn-system
{{- end -}}