apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: { { .Release.Name } }
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      name: "{{ .Release.Name }}"
    - namespace: "*"
      name: "in-cluster"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
