apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: {{ .Release.Name }}-talos-cp
spec:
  version: {{ .Values.kubernetes.version }}
  replicas: {{ .Values.controlPlane.replicas }}
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: {{ .Release.Name }}-cp
    namespace: default
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      strategicPatches:
      - |
        - op: replace
          path: /machine/install
          value:
            disk: /dev/sda
            extensions:
              - image: {{ .Values.extensions.qemuGuestAgent.image }}
        - op: replace
          path: /cluster/allowSchedulingOnControlPlanes
          value: {{.Values.controlPlane.allowScheduling}}
        - op: add
          path: /machine/install/extraKernelArgs
          value:
            - net.ifnames=0
        - op: add
          path: /machine/network/interfaces
          value:
            - interface: eth0
              dhcp: false
              vip:
                ip: {{ .Values.network.vip }}
        {{ if .Values.controlPlane.tccm -}}
        - op: add
          path: /machine/kubelet/extraArgs
          value:
              cloud-provider: external
        - op: add
          path: /machine/features/kubernetesTalosAPIAccess
          value:
            enabled: true
            allowedRoles:
              - os:reader
            allowedKubernetesNamespaces:
              - kube-system
        - op: add
          path: /cluster/externalCloudProvider
          value:
            enabled: true
            manifests:
              - {{ .Values.controlPlane.cloudProvider }}
        {{- end }}
        {{ if .Values.cilium.enabled -}}
        - op: add
          path: /cluster/network/cni/name
          value: none
        - op: replace
          path: /cluster/network/proxy/disabled
          value: true
        {{- end }}
        - op: add
          path: /cluster/apiServer/admissionControl/0/configuration/exemptions/namespaces/-
          value: falco
