{{- if .Values.worker.enabled -}}
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: {{ .Release.Name }}-workers
spec:
  template:
    spec:
      generateType: worker
      talosVersion: {{ .Values.controlPlane.version }}
      strategicPatches:
      - |
        - op: add
          path: /machine/install/extraKernelArgs
          value:
            - net.ifnames=0
        - op: add
          path: /machine/kubelet/extraArgs/rotate-server-certificates
          value: "true"
        - op: add
          path: /machine/kubelet/extraMounts
          value: []
        - op: add
          path: /machine/sysctls
          value:
            net.ipv4.ip_forward: 1
            net.ipv6.conf.all.forwarding: 1
            vm.nr_hugepages: 2048
        - op: add
          path: /cluster/apiServer/admissionControl/0/configuration/exemptions/namespaces/-
          value: falco
        {{ if .Values.controlPlane.tccm -}}
        - op: add
          path: /machine/kubelet/extraArgs
          value:
              cloud-provider: external
        {{- end }}
        {{ if .Values.cilium.enabled -}}
        - op: add
          path: /cluster/network/cni
          value:
            name: none
        - op: add
          path: /cluster/proxy
          value:
            disabled: true
        - op: replace
          path: /cluster/network/podSubnets
          value:
            {{- range $index, $subnet := .Values.cilium.podSubnets }}
            - {{ $subnet }}
            {{- end }}
        - op: replace
          path: /cluster/network/serviceSubnets
          value:
            {{- range $index, $subnet := .Values.cilium.serviceSubnets }}
            - {{ $subnet }}
            {{- end }}
        {{- end }}
        {{ if .Values.storage.local.enabled -}}
        - op: add
          path: /machine/kubelet/extraMounts/-
          value:
            source: /var/local-path-provisioner
            destination: /var/local-path-provisioner
            type: bind
            options:
              - bind
              - rshared
              - rw
        {{- end }}
        {{ if .Values.storage.longhorn.enabled -}}
        - op: add
          path: /machine/kubelet/extraMounts/-
          value:
            source: /var/lib/longhorn
            destination: /var/lib/longhorn
            type: bind
            options:
              - bind
              - rshared
              - rw
        - op: add
          path: /machine/kernel
          value:
            modules:
              - name: nvme_tcp
              - name: vfio_pci
        {{- end }}
{{- end -}}