kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "create-sa-pvc-{{ .Release.Name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path