apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-secret
  namespace: cert-manager
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: cert-store
  target:
    name: weebo.poc
  data:
  - secretKey: cert-ca
    remoteRef:
      key: mv/cert-manager/config
      property: fullcert_chain