apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: headlamp
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    targetRevision: 0.30.1
    helm:
      releaseName: headlamp
      valuesObject:
        config:
          inCluster: true
          extraArgs:
          - --kubeconfig=/kubeconfig/main-cluster/value
        volumes:
        - name: main-cluster
          secret:
            secretName: main-cluster-kubeconfig
        volumeMounts:
        - name: main-cluster
          mountPath: /kubeconfig/main-cluster
        env:
        - name: KUBECONFIG
          value: /kubeconfig/main-cluster/value:/home/headlamp/.config/Headlamp/kubeconfigs/config
        serviceAccount:
          create: true
        service:
          port: 8080
        extraManifests:
        - |
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: headlamp-admin
            namespace: default
        - |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: headlamp-admin-2
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: headlamp-admin
            namespace: default
        - |
          apiVersion: v1
          kind: Secret
          metadata:
            name: headlamp-admin-secret
            namespace: default
            annotations:
              kubernetes.io/service-account.name: headlamp-admin
          type: kubernetes.io/service-account-token
        - |
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: headlamp
            namespace: default
          spec:
            secretName: headlamp-tls
            issuerRef:
              name: vault-issuer
              kind: ClusterIssuer
            commonName: headlamp.capi.weebo.poc
            dnsNames:
            - headlamp.capi.weebo.poc
        - |
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: headlamp
            namespace: default
          spec:
            entryPoints:
            - websecure
            routes:
            - kind: Rule
              match: Host(`headlamp.capi.weebo.poc`)
              priority: 10
              services:
              - name: headlamp
                port: 8080
            tls:
              secretName: headlamp-tls
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
