{{- if .Values.angos.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: angos
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: angos
  ports:
    - port: 8000
      targetPort: 8000
{{- end -}}