apiVersion: batch/v1
kind: Job
metadata:
  name: mono-node-create-sa-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: create-webhook
        command:
        - /bin/bash
        - '-c'
        - |
          set -x
          ansible-playbook -i localhost /scripts/playbook.yaml
        image: quay.io/agnosticd/ee-multicloud:latest
        volumeMounts:
        - mountPath: /scripts
          name: mono-node-script-vol
        - mountPath: /tokens
          name: kube-secret
      restartPolicy: Never
      volumes:
      - name: mono-node-script-vol
        configMap:
          name: mono-node-create-sa
      - name: kube-secret
        secret:
          secretName: mono-node-kubeconfig
