apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-ci-role
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - list
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-default-ci-role
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-ci-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
