storage:
  local:
    enabled: true

kubevirt:
  enabled: true
  storageClass: local-storage

dns:
  outbound:
    enabled: true
    name: "4.weebo.fr"
  inbound:
    enabled: true
    wildcard: true
    base: weebo.poc
    name: "{{.Release.Name}}"

vault:
  enabled: true

certManager:
  enabled: true
  version: 1.18.0
  installCRDs: true

trustManager:
  enabled: true
  version: 0.17.1

traefik:
  enabled: true
  version: 36.1.0
  ips: "37.187.255.5,2001:41d0:c:705::1"
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2
    sablier:
      moduleName: github.com/sablierapp/sablier
      version: v1.9.0