storage:
  local:
    enabled: true

kubevirt:
  enabled: true
  manager: true
  storageClass: local-storage

dns:
  outbound:
    enabled: true
    name: "4.weebo.fr"
  inbound:
    enabled: true
    wildcard: true
    base: weebo.poc
    name: "{{.Release.Name}}"

omni:
  enabled: true

clusterApi:
  enabled: true
  version:
    operator: 0.22.0
    clusterApi: v1.10.4
    kubevirt: v0.1.10
    talosCP: v0.5.10
    talosBootstrap: v0.6.9
    ipam: v1.0.3
    helmAddon: v0.3.2

vault:
  enabled: true

netbird:
  enabled: true

certManager:
  enabled: true
  version: 1.18.0
  installCRDs: true

trustManager:
  enabled: true
  version: 0.17.1

externalSecrets:
  enabled: true
  version: 0.17.0
  vault:
    enabled: true
    version: 4.4.0

auth:
  enabled: true
  version: 2025.8.1

glance:
  enabled: true

traefik:
  enabled: true
  version: 37.0.0
  ips: "37.187.255.5,2001:41d0:c:705::1"
  kubeCRD:
    enabled: true
  kubeIngress:
    enabled: true
  gatewayAPI:
    enabled: false
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2
    sablier:
      moduleName: github.com/sablierapp/sablier
      version: v1.9.0