{{ $inDns := print (tpl .Values.dns.name .) "." .Values.dns.in.base }}
{{ $outDns := print (tpl .Values.dns.name .) "." .Values.dns.out.base }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: "{{ .Release.Name }}-websecure"
  namespace: "{{ .Release.Namespace }}"
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI("{{ $inDns }}") || HostSNIRegexp(`^.+\.{{ regexReplaceAll "\\." $inDns "\\." }}$`)
      services:
        - name: "{{ .Release.Name }}"
          namespace: "{{ .Release.Namespace }}"
          port: 443
    - match: HostSNI("{{ $outDns }}") || HostSNIRegexp(`^.+\.{{ regexReplaceAll "\\." $outDns "\\." }}$`)
      services:
        - name: "{{ .Release.Name }}"
          namespace: "{{ .Release.Namespace }}"
          port: 443
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
#kind: IngressRouteTCP
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}-web"
  namespace: "{{ .Release.Namespace }}"
spec:
  entryPoints:
    - web
  routes:
    - match: Host("{{ $inDns }}") || HostRegexp(`^.+\.{{ regexReplaceAll "\\." $inDns "\\." }}$`)
      services:
        - name: "{{ .Release.Name }}"
          namespace: "{{ .Release.Namespace }}"
          port: 80
    - match: Host("{{ $outDns }}") || HostRegexp(`^.+\.{{ regexReplaceAll "\\." $outDns "\\." }}$`)
      services:
        - name: "{{ .Release.Name }}"
          namespace: "{{ .Release.Namespace }}"
          port: 80