{{ $inDns := printf "{{ tpl .Values.dns.name . }}.{{.Values.dns.in.base}}" }}
{{ $outDns := printf "{{ tpl .Values.dns.name . }}.{{.Values.dns.out.base}}" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: "{{ .Release.Name }}-websecure"
  namespace: "{{ .Release.Namespace }}"
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI("{{ .$inDns }}") || HostSNIRegexp(`^.+{{ regexReplaceAll "\." .$inDns "\\." }}$`)
      services:
        - name: "{{ .Release.Name }}"
          port: 8443
      middlewares:
        - name: vpn-only
          namespace: traefik
    - match: HostSNI("{{ .$outDns }}") || HostSNIRegexp(`^.+{{ regexReplaceAll "\." .$outDns "\\." }}$`)
      services:
        - name: "{{ .Release.Name }}"
          port: 8443
  tls:
    passthrough: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: "{{ .Release.Name }}-web"
  namespace: "{{ .Release.Namespace }}"
spec:
  entryPoints:
    - web
  routes:
    - match: HostSNI("{{ .$inDns }}") || HostSNIRegexp(`^.+{{ regexReplaceAll "\." .$inDns "\\." }}$`)
      services:
        - name: "{{ .Release.Name }}"
          port: 8080
      middlewares:
        - name: vpn-only
          namespace: traefik
    - match: HostSNI("{{ .$outDns }}") || HostSNIRegexp(`^.+{{ regexReplaceAll "\." .$outDns "\\." }}$`)
      services:
        - name: "{{ .Release.Name }}"
          port: 8080
  tls:
    passthrough: true