{{ $inDns := print (tpl .Values.dns.name .) "." .Values.dns.in.base }}

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ $inDns }},*.{{ $inDns }}"
    external-dns.alpha.kubernetes.io/internal-hostname: "{{ $inDns }},*.{{ $inDns }}"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    cluster.x-k8s.io/cluster-name: "{{ .Release.Name }}"
  type: ClusterIP
