{{- if .Values.traefik.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Release.Name }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: {{ .Values.traefik.version }}
    helm:
      releaseName: traefik
      valuesObject:
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: (Host("{{ tpl .Values.dns.name . }}.{{.Values.dns.out.base}}") || Host("{{ tpl .Values.dns.name . }}.{{.Values.dns.in.base}}")) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            entryPoints:
            - web
        service:
          annotations:
            lbipam.cilium.io/sharing-key: "weebo-gate"
            lbipam.cilium.io/ips: "{{ .Values.traefik.ips }}"
            lbipam.cilium.io/sharing-cross-namespace: "*"
        logs:
          general:
            format: json
          access:
            enabled: true
            format: json
            fields:
              headers:
                defaultMode: keep
                names:
                  Authorization: redact
        providers:
          kubernetesCRD:
            enabled: {{ .Values.traefik.kubeCRD.enabled }}
            allowCrossNamespace: true
          kubernetesIngress:
            enabled: {{ .Values.traefik.kubeIngress.enabled }}
            allowEmptyServices: true
            allowExternalNameServices: true
            publishedService:
              enabled: true
          kubernetesGateway:
            enabled: {{ .Values.traefik.gatewayAPI.enabled }}
  destination:
    name: {{ .Release.Name }}
    namespace: 'traefik'
{{- end -}}