apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "kube-certificate"
  namespace: "omni"
spec:
  commonName: "kube.omni.4.weebo.fr"
  secretName: "kube-certificate"
  dnsNames:
    - "kube.omni.4.weebo.fr"
  issuerRef:
    kind: ClusterIssuer
    name: "outbound"
