apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ui
  namespace: omni
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`omni.4.weebo.fr`) && PathPrefix(`/`)
      services:
        - name: internal
          namespace: omni
          passHostHeader: true
          port: 8080
  tls:
    secretName: omni-certificate
