version: '3'

tasks:
  create-talos-image:
    dir: ./0.ansible/talos-img
    cmds:
    - echo "Create and download Talos image"
    - ansible-playbook -i ../inventories/inventory.proxmox.yml site.yml --vault-password-file=../../vault_password
