version: '3'

env:
  NODE_IP: 192.168.100.210

tasks:
  init-capi:
    dir: ./.talos-capi
    cmds:
    - echo "Bootstrap Talos"
    - talosctl gen secrets
    - talosctl gen config capi https://$NODE_IP:6443
    - echo "Init control plane"
    - talosctl apply-config --insecure --nodes $NODE_IP --file controlplane.yaml
    - echo "Bootstrap Talos"
    - talosctl bootstrap -n $NODE_IP -e $NODE_IP --talosconfig ./talosconfig
  get-kubeconfig-capi:
    dir: ./.talos-capi
    cmds:
    - echo "Get kubeconfig"
    - talosctl kubeconfig . -e $NODE_IP -n $NODE_IP --talosconfig ./talosconfig
  init:
    dir: ./0.terraform/download-iso-talos
    cmds:
    - echo "Download Talos ISO"
    - terraform init -upgrade
    - TF_VAR_proxmox_api="${PROXMOX_URL}" TF_VAR_proxmox_api_token="${PROXMOX_USER}!${PROXMOX_TOKEN_ID}=${PROXMOX_TOKEN_SECRET}" TF_VAR_proxmox_ssh_username="${PROXMOX_NODE}" TF_VAR_proxmox_node_name="${PROXMOX_NODE}" terraform apply {{ .CLI_ARGS }}
  install-talos:
    dir: ./0.terraform/install-vm-talos
    silent: true
    cmds:
      - echo "Install Talos"
      - terraform init
      - TF_VAR_ssh_public_key="${SSH_KEY}" TF_VAR_fqdn="${PROXMOX_DNS}" TF_VAR_ovh_server_name="${SERVER_NAME}" terraform apply
  install-talos2:
    dir: ./0.terraform/install-vm-talos-2
    silent: true
    cmds:
      - echo "Install Talos"
      - terraform init
      - TF_VAR_ssh_public_key="${SSH_KEY}" TF_VAR_fqdn="${PROXMOX_DNS}" TF_VAR_ovh_server_name="${SERVER_NAME}" terraform apply
  k9s:
    env:
      KUBECONFIG: ./0.terraform/install-vm-talos/kubeconfig
    cmds:
      - k9s {{ .CLI_ARGS }}
  talosctl:
    env:
      TALOSCONFIG: ./0.terraform/install-vm-talos/talos-config.yaml
    cmds:
      - talosctl {{ .CLI_ARGS }}
  kubectl:
    env:
      KUBECONFIG: ./0.terraform/install-vm-talos/kubeconfig
    cmds:
    - kubectl {{ .CLI_ARGS }}
  cilium:
    env:
      KUBECONFIG: ./0.terraform/install-vm-talos/kubeconfig
    cmds:
      - cilium {{ .CLI_ARGS }}
