version: '3'

env:
  KUBECONFIG: "./capi.terraform/kubeconfig"

tasks:
  kubectl:
    cmds:
    - kubectl {{ .CLI_ARGS }}
  init-proxmox:
    dir: capi.terraform
    cmds:
    - echo "Init proxmox CAPI node"
    - terraform init
    - TF_VAR_proxmox_api="${PROXMOX_URL}" TF_VAR_proxmox_api_token="${PROXMOX_USER}!${PROXMOX_TOKEN_ID}=${PROXMOX_TOKEN_SECRET}" TF_VAR_proxmox_ssh_username="${PROXMOX_NODE}" TF_VAR_proxmox_node_name="${PROXMOX_NODE}" terraform apply {{ .CLI_ARGS }}
