version: '3'

env:
  KUBECONFIG: "{{.ROOT_DIR}}/capi.terraform/kubeconfig"
  ARGO_APP_REPO: "https://github.com/batleforc/weebo-si"
  ARGO_DEST_SERVER: "https://kubernetes.default.svc"
  ARGO_VERSION: "7.8.7"

includes:
  argo:
    taskfile: ./argo/Taskfile.yml
  cluster:
    taskfile: ./cluster/Taskfile.yml
  vault:
    taskfile: ./vault/Taskfile.yml

tasks:
  kubectl:
    cmds:
    - echo $KUBECONFIG
    - kubectl {{ .CLI_ARGS }}
  k9s:
    cmds:
    - k9s {{ .CLI_ARGS }}
  talosctl:
    env:
      TALOSCONFIG: "./capi.terraform/talos-config.yaml"
    cmds:
    - talosctl {{ .CLI_ARGS }}
  init:
    dir: capi.terraform
    cmds:
    - echo "Init CAPI node with Proxmox and Talos"
    - terraform init
    - TF_VAR_proxmox_api="${PROXMOX_URL}" TF_VAR_proxmox_api_token="${PROXMOX_USER}!${PROXMOX_TOKEN_ID}=${PROXMOX_TOKEN_SECRET}" TF_VAR_proxmox_ssh_username="${PROXMOX_NODE}" TF_VAR_proxmox_node_name="${PROXMOX_NODE}" terraform apply {{ .CLI_ARGS }}
  init-provider:
    dir: capi.terraform_init
    cmds:
    - echo "Create capi ns and prepare provider"
    - terraform init
    - TF_VAR_proxmox_api="${PROXMOX_URL}" TF_VAR_proxmox_api_token="${PROXMOX_USER}!${PROXMOX_TOKEN_ID}" TF_VAR_proxmox_secret="${PROXMOX_TOKEN_SECRET}" terraform apply {{ .CLI_ARGS }}
  destroy:
    dir: capi.terraform
    cmds:
    - echo "Destroy CAPI node with Proxmox and Talos"
    - TF_VAR_proxmox_api="${PROXMOX_URL}" TF_VAR_proxmox_api_token="${PROXMOX_USER}!${PROXMOX_TOKEN_ID}=${PROXMOX_TOKEN_SECRET}" TF_VAR_proxmox_ssh_username="${PROXMOX_NODE}" TF_VAR_proxmox_node_name="${PROXMOX_NODE}" terraform destroy {{ .CLI_ARGS }}
  headlamp:
    cmds:
    - kubectl get secret headlamp-admin-secret -n default -o jsonpath='{.data.token}' | base64 --decode

  install-csr:
    cmds:
    - kubectl apply -f ./capi.argo/infra/cert-approver/app.yaml
