apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo
  namespace: argocd
spec:
  entryPoints:
  - web
  routes:
  - match: PathPrefix(`/argo`)
    kind: Rule
    services:
    - name: argocd-server
      port: 443
      namespace: argocd
