apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: multi-node
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 34.4.1
    helm:
      releaseName: traefik
      valuesObject:
        ingressRoute:
          dashboard:
            enabled: true
        service:
          annotations:
            metallb.universe.tf/address-pool: one
            metallb.io/ip-allocated-from-pool: one
        logs:
          general:
            format: json
          access:
            enabled: true
            format: json
            fields:
              headers:
                defaultMode: keep
                names:
                  Authorization: redact
        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
          kubernetesIngress:
            allowEmptyServices: true
            allowExternalNameServices: true
            publishedService:
              enabled: true
  destination:
    name: "multi-node"
    namespace: traefik
