certManager:
  enabled: true
  # renovate: datasource=docker depName=quay.io/jetstack/charts/cert-manager
  version: v1.21.1
  installCRDs: true
  certIssuer:
    enabled: true
    name: outbound
    email: "maxleriche.60@gmail.com"
  certIssuerDNS01:
    enabled: false
    name: dns-01
    email: "maxleriche.60@gmail.com"
    nameservers: "dns-server-in.dns.svc.cluster.local"
    namespace: "dns"

trustManager:
  enabled: true
  # renovate: datasource=docker depName=quay.io/jetstack/charts/trust-manager
  version: "0.24.0"
  installCRDs: true

traefik:
  enabled: true
  # renovate: datasource=docker depName=ghcr.io/traefik/helm/traefik
  version: 40.2.0
  ips: ""
  kubeCRD:
    enabled: true
  kubeIngress:
    enabled: true
  gatewayAPI:
    enabled: false

authentik:
  enabled: true

repo: ""
project: ""
branch: ""

subApp:
  enabled: true
